/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.4 Sun Feb 13 10:10:30 2022.
 */

#ifndef FM29_NFC_READERS_CAN_V1_0_INTERIOR_H
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_H

#ifdef __cplusplus
extern "C" {
#endif

#include "PE_Types.h"
#include "stddef.h"

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#if 0
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X205_SEC_DATA_04_FRAME_ID (0x205u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X204_SEC_DATA_03_FRAME_ID (0x204u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X203_SEC_DATA_02_FRAME_ID (0x203u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X202_SEC_DATA_01_FRAME_ID (0x202u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X24_SEC_DATA_04_FRAME_ID (0x24u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X23_SEC_DATA_03_FRAME_ID (0x23u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X21_SEC_DATA_01_FRAME_ID (0x21u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X22_SEC_DATA_02_FRAME_ID (0x22u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_FRAME_ID (0x20u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X201_EXTENDED_STS_FRAME_FRAME_ID (0x201u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_FRAME_ID (0x200u)
#endif

#if 1
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X205_SEC_DATA_04_FRAME_ID (0x105u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X204_SEC_DATA_03_FRAME_ID (0x104u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X203_SEC_DATA_02_FRAME_ID (0x103u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X202_SEC_DATA_01_FRAME_ID (0x102u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X24_SEC_DATA_04_FRAME_ID (0x14u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X23_SEC_DATA_03_FRAME_ID (0x13u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X21_SEC_DATA_01_FRAME_ID (0x11u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X22_SEC_DATA_02_FRAME_ID (0x12u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_FRAME_ID (0x10u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X201_EXTENDED_STS_FRAME_FRAME_ID (0x101u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_FRAME_ID (0x100u)
#endif

/* Frame lengths in bytes. */
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X205_SEC_DATA_04_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X204_SEC_DATA_03_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X203_SEC_DATA_02_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X202_SEC_DATA_01_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X24_SEC_DATA_04_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X23_SEC_DATA_03_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X21_SEC_DATA_01_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X22_SEC_DATA_02_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X201_EXTENDED_STS_FRAME_LENGTH (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_LENGTH (8u)

/* Extended or standard frame types. */
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X205_SEC_DATA_04_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X204_SEC_DATA_03_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X203_SEC_DATA_02_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X202_SEC_DATA_01_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X24_SEC_DATA_04_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X23_SEC_DATA_03_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X21_SEC_DATA_01_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X22_SEC_DATA_02_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X201_EXTENDED_STS_FRAME_IS_EXTENDED (0)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_CYCLE_TIME_MS (10u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X201_EXTENDED_STS_FRAME_CYCLE_TIME_MS (20u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_CYCLE_TIME_MS (15u)

/* Signal choices. */
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_SCU_NFC_INT_CMD_VEHICLE_LOCKED__DEFAULT__LOCKED__CHOICE (0u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_SCU_NFC_INT_CMD_VEHICLE_LOCKED_UNLOCKED_CHOICE (2u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_SCU_NFC_INT_CMD_VEHICLE_LOCKED_LOCKED_CHOICE (3u)

#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_SCU_NFC_INT_CMD_VEHICLE_MOVING__DEFAULT__IN_MOTION__CHOICE (0u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_SCU_NFC_INT_CMD_VEHICLE_MOVING_STATIC_CHOICE (2u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_SCU_0X20_COMMAND_SCU_NFC_INT_CMD_VEHICLE_MOVING_IN_MOTION_CHOICE (3u)

#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_NO_FAULT_CHOICE (0u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___ACTUATOR_FAILURE_CHOICE (1u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___INVALID_VALUE_2_CHOICE (2u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___INVALID_VALUE_3_CHOICE (3u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___CLAW_SENSOR_FAILURE_CHOICE (4u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___ENCODER_FEEDBACK_CHOICE (5u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___INVALID_VALUE_6_CHOICE (6u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___OVER_TEMPERATURE_CHOICE (7u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___UNDER_VOLTAGE_CHOICE (8u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___OVER_VOLTAGE_CHOICE (9u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___OPERATION_DENIED_CHOICE (10u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___DOOR_ICED_CHOICE (11u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___CLINCH_OBSTRUCTED_CHOICE (12u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___MOTOR_STALLED_CHOICE (13u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_FAILURE___FAILED_TO_CLINCH_CHOICE (14u)
#define FM29_NFC_READERS_CAN_V1_0_INTERIOR_NFC_INT_0X200_STATUS_FRAME_NFC_INT_SCU_STS_FAILURE_DEFAULT__NO_FAULT__CHOICE (15u)

/**
 * Signals in message NFCInt_0x205_SecData_04.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data04_byte7;
};

/**
 * Signals in message NFCInt_0x204_SecData_03.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte6;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data03_byte7;
};

/**
 * Signals in message NFCInt_0x203_SecData_02.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data02_byte7;
};

/**
 * Signals in message NFCInt_0x202_SecData_01.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sec_data01_byte7;
};

/**
 * Signals in message SCU_0x24_SecData_04.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data04_byte7;
};

/**
 * Signals in message SCU_0x23_SecData_03.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data03_byte7;
};

/**
 * Signals in message SCU_0x21_SecData_01.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data01_byte7;
};

/**
 * Signals in message SCU_0x22_SecData_02.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_t {
    /**
     * LSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte6;

    /**
     * MSB for Arrays
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_sec_data02_byte7;
};

/**
 * Signals in message SCU_0x20_Command.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_cmd_update_byte;

    /**
     * Rear Left Door Vehicle Locked Signal
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_cmd_vehicle_locked;

    /**
     * Rear Left Door Vehicle Moving Signal
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_cmd_vehicle_moving;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_cmd_enable_nfc;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_cmd_pairing;

    /**
     * Rear Left Door Command Message Counter - Value has to be incremented on each transmission of the command frame. Only frames with consecutive command counter values are valid.
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t scu_nfc_int_cmd_counter;
};

/**
 * Signals in message NFCInt_0x201_ExtendedStsFrame.
 *
 * Internal signals, not used in normal operation
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte0;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte1;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte2;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte3;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte4;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte5;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte6;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_extended_status_byte7;
};

/**
 * Signals in message NFCInt_0x200_StatusFrame.
 *
 * All signal values are as on the CAN bus.
 */
struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_update_byte;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_nfc_tag_status;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_nfc_tag_auth_status;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_pairing_mode;

    /**
     * Rear Left Door Latch Failure status
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_failure;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_key_id;

    /**
     * Rear Left Door Status Message Counter
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t nfc_int_scu_sts_counter;
};

/**
 * Pack message NFCInt_0x205_SecData_04.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_t *src_p,
    size_t size);

/**
 * Unpack message NFCInt_0x205_SecData_04.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte7_is_in_range(uint8_t value);

/**
 * Pack message NFCInt_0x204_SecData_03.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_t *src_p,
    size_t size);

/**
 * Unpack message NFCInt_0x204_SecData_03.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte7_is_in_range(uint8_t value);

/**
 * Pack message NFCInt_0x203_SecData_02.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_t *src_p,
    size_t size);

/**
 * Unpack message NFCInt_0x203_SecData_02.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte7_is_in_range(uint8_t value);

/**
 * Pack message NFCInt_0x202_SecData_01.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_t *src_p,
    size_t size);

/**
 * Unpack message NFCInt_0x202_SecData_01.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte7_is_in_range(uint8_t value);

/**
 * Pack message SCU_0x24_SecData_04.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_t *src_p,
    size_t size);

/**
 * Unpack message SCU_0x24_SecData_04.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte7_is_in_range(uint8_t value);

/**
 * Pack message SCU_0x23_SecData_03.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_t *src_p,
    size_t size);

/**
 * Unpack message SCU_0x23_SecData_03.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte7_is_in_range(uint8_t value);

/**
 * Pack message SCU_0x21_SecData_01.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_t *src_p,
    size_t size);

/**
 * Unpack message SCU_0x21_SecData_01.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte7_is_in_range(uint8_t value);

/**
 * Pack message SCU_0x22_SecData_02.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_t *src_p,
    size_t size);

/**
 * Unpack message SCU_0x22_SecData_02.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte7_is_in_range(uint8_t value);

/**
 * Pack message SCU_0x20_Command.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_t *src_p,
    size_t size);

/**
 * Unpack message SCU_0x20_Command.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_update_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_update_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_update_byte_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_locked_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_locked_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_locked_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_moving_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_moving_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_moving_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_enable_nfc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_enable_nfc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_enable_nfc_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_pairing_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_pairing_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_pairing_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_counter_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_counter_is_in_range(uint8_t value);

/**
 * Pack message NFCInt_0x201_ExtendedStsFrame.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_t *src_p,
    size_t size);

/**
 * Unpack message NFCInt_0x201_ExtendedStsFrame.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte0_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte0_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte0_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte3_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte4_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte4_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte4_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte5_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte5_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte5_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte6_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte6_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte6_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte7_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte7_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte7_is_in_range(uint8_t value);

/**
 * Pack message NFCInt_0x200_StatusFrame.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_t *src_p,
    size_t size);

/**
 * Unpack message NFCInt_0x200_StatusFrame.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_update_byte_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_update_byte_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_update_byte_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_auth_status_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_auth_status_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_auth_status_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_pairing_mode_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_pairing_mode_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_pairing_mode_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_failure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_failure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_failure_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_key_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_key_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_key_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_counter_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_counter_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_counter_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
