/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.4 Sun Feb 13 10:10:30 2022.
 */

#include <string.h>

#include "fm29_nfc_readers_can_v1_0_interior.h"

static /*inline*/ uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static /*inline*/ uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data04_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nfc_int_scu_sec_data04_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data04_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x205_sec_data_04_nfc_int_scu_sec_data04_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data03_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nfc_int_scu_sec_data03_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data03_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x204_sec_data_03_nfc_int_scu_sec_data03_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data02_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nfc_int_scu_sec_data02_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data02_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x203_sec_data_02_nfc_int_scu_sec_data02_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->nfc_int_scu_sec_data01_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nfc_int_scu_sec_data01_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->nfc_int_scu_sec_data01_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x202_sec_data_01_nfc_int_scu_sec_data01_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data04_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->scu_nfc_int_sec_data04_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data04_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x24_sec_data_04_scu_nfc_int_sec_data04_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data03_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->scu_nfc_int_sec_data03_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data03_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x23_sec_data_03_scu_nfc_int_sec_data03_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data01_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->scu_nfc_int_sec_data01_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data01_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x21_sec_data_01_scu_nfc_int_sec_data01_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->scu_nfc_int_sec_data02_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->scu_nfc_int_sec_data02_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->scu_nfc_int_sec_data02_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x22_sec_data_02_scu_nfc_int_sec_data02_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->scu_nfc_int_cmd_update_byte, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_cmd_vehicle_locked, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_cmd_vehicle_moving, 2u, 0x0cu);
    dst_p[1] |= pack_left_shift_u8(src_p->scu_nfc_int_cmd_enable_nfc, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->scu_nfc_int_cmd_pairing, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->scu_nfc_int_cmd_counter, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->scu_nfc_int_cmd_update_byte = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->scu_nfc_int_cmd_vehicle_locked = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->scu_nfc_int_cmd_vehicle_moving = unpack_right_shift_u8(src_p[1], 2u, 0x0cu);
    dst_p->scu_nfc_int_cmd_enable_nfc = unpack_right_shift_u8(src_p[1], 4u, 0x30u);
    dst_p->scu_nfc_int_cmd_pairing = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->scu_nfc_int_cmd_counter = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_update_byte_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_update_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_update_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_locked_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_locked_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_locked_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_moving_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_moving_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_vehicle_moving_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_enable_nfc_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_enable_nfc_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_enable_nfc_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_pairing_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_pairing_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_pairing_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_counter_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_scu_0x20_command_scu_nfc_int_cmd_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte0, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte3, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte4, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte5, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte6, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->nfc_int_scu_extended_status_byte7, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nfc_int_scu_extended_status_byte0 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->nfc_int_scu_extended_status_byte7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte0_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte0_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte0_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte1_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte1_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte2_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte2_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte3_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte3_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte4_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte4_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte5_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte5_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte6_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte6_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte7_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte7_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x201_extended_sts_frame_nfc_int_scu_extended_status_byte7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_pack(
    uint8_t *dst_p,
    const struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_update_byte, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_nfc_tag_status, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_nfc_tag_auth_status, 2u, 0x3cu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_pairing_mode, 0u, 0x0fu);
    dst_p[2] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_failure, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_key_id, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->nfc_int_scu_sts_counter, 0u, 0xffu);

    return (8);
}

int fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_unpack(
    struct fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->nfc_int_scu_sts_update_byte = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->nfc_int_scu_sts_nfc_tag_status = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->nfc_int_scu_sts_nfc_tag_auth_status = unpack_right_shift_u8(src_p[1], 2u, 0x3cu);
    dst_p->nfc_int_scu_sts_pairing_mode = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->nfc_int_scu_sts_failure = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->nfc_int_scu_sts_key_id = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->nfc_int_scu_sts_counter = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_update_byte_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_update_byte_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_update_byte_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_status_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_status_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_auth_status_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_auth_status_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_nfc_tag_auth_status_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_pairing_mode_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_pairing_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_pairing_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_failure_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_failure_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_failure_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_key_id_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_key_id_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_key_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_counter_encode(double value)
{
    return (uint8_t)(value);
}

double fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool fm29_nfc_readers_can_v1_0_interior_nfc_int_0x200_status_frame_nfc_int_scu_sts_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
