/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ADC_Port_AD.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_ADC
**     Version   : Component 01.218, Driver 01.12, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 17/09/2021, 15:43
**     Abstract  :
**          This file implements the ADC (ADC) module initialization
**          according to the Peripheral Initialization Component settings,
**          and defines interrupt service routines prototypes.The ADC module
**          is an 8-channel (16-channel), 10-bit, multiplexed input successive
**          approximation analog-to-digital converter. Refer to device electrical
**          specifications for ATD accuracy. The block is designed to be
**          upwards compatible with the 68HC11 standard 8-bit A/D converter.
**          In addition, there are new operating modes that are unique to
**          the HC12 design.
**          Features :
**          - 8/10 Bit Resolution.
**          - 7msec, 10-Bit Single Conversion Time.
**          - Sample Buffer Amplifier.
**          - Programmable Sample Time.
**          - Left/Right Justified, Signed/Unsigned Result Data.
**          - External Trigger Control.
**          - Conversion Completion Interrupt Generation.
**          - Analog Input Multiplexer for 8 (16)Analog Input Channels.
**          - Analog/Digital Input Pin Multiplexing.
**          - 1 to 8 (1 to 16)Conversion Sequence Lengths.
**          - Continuous Conversion Mode.
**          - Multiple Channel Scans.
**     Settings  :
**          Component name                                 : ADC_Port_AD
**          Device                                         : ADC
**          Settings                                       : 
**            Clock settings                               : 
**              Discharge before sampling                  : no
**              Sample time                                : 4 A/D conversion clock periods
**              Prescaler                                  : 5
**              Frequency                                  : 2083.3 kHz
**              Conversion time                            : 9.1 us
**            Conv. sequence length                        : 4
**            Conversion mode                              : Single conversion
**            Channel sample mode                          : Only one channel
**            Result data formats                          : 10-bit/left justified/unsigned
**            Fast flag clear all                          : Disabled
**            Wrap around channel                          : AN11
**            External trigger                             : Disabled
**            External trigger control                     : Falling edge
**            Conv. results are placed in                  : Corresponding result register
**            Background debug freeze                      : Continue conversion
**            Special channel conversion                   : Disabled
**            Number of automatic comparison               : 0
**          Pins/Signals                                   : 
**            External trigger                             : no
**            ADC input pins                               : 4
**              Input Pin0                                 : 
**                Pin                                      : PAD0_KWAD0_AN0
**                Pin Signal                               : HBR_HSD_ISENSB_ADC
**                Digital Input                            : Disabled
**              Input Pin1                                 : 
**                Pin                                      : PAD1_KWAD1_AN1
**                Pin Signal                               : HBR_HSD_ISENSA_ADC
**                Digital Input                            : Disabled
**              Input Pin2                                 : 
**                Pin                                      : PAD2_KWAD2_AN2
**                Pin Signal                               : SNS_VSENS_ADC
**                Digital Input                            : Disabled
**              Input Pin3                                 : 
**                Pin                                      : PAD3_KWAD3_AN3
**                Pin Signal                               : SNS_TSENS_ADC
**                Digital Input                            : Disabled
**          Interrupts                                     : 
**            Sequence Complete                            : 
**              Sequence complete interrupt                : Disabled
**              Interrupt                                  : Vatd
**              Priority                                   : 1
**              ISR name                                   : 
**            Compare                                      : 
**              Compare interrupt                          : Disabled
**              Interrupt                                  : Vatdcompare
**              Priority                                   : 1
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Start ADC conversion                         : no
**     Contents  :
**         Init - void ADC_Port_AD_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
#ifndef __ADC_Port_AD
#define __ADC_Port_AD

/* MODULE ADC_Port_AD. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"





void ADC_Port_AD_Init(void);
/*
** ===================================================================
**     Method      :  ADC_Port_AD_Init (component Init_ADC)
**
**     Description :
**         This method initializes registers of the ADC module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END ADC_Port_AD. */

#endif /* ifndef __ADC_Port_AD */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
