/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ADC_Port_AD.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_ADC
**     Version   : Component 01.218, Driver 01.12, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 12/07/2022, 20:44
**     Abstract  :
**          This file implements the ADC (ADC) module initialization
**          according to the Peripheral Initialization Component settings,
**          and defines interrupt service routines prototypes.The ADC module
**          is an 8-channel (16-channel), 10-bit, multiplexed input successive
**          approximation analog-to-digital converter. Refer to device electrical
**          specifications for ATD accuracy. The block is designed to be
**          upwards compatible with the 68HC11 standard 8-bit A/D converter.
**          In addition, there are new operating modes that are unique to
**          the HC12 design.
**          Features :
**          - 8/10 Bit Resolution.
**          - 7msec, 10-Bit Single Conversion Time.
**          - Sample Buffer Amplifier.
**          - Programmable Sample Time.
**          - Left/Right Justified, Signed/Unsigned Result Data.
**          - External Trigger Control.
**          - Conversion Completion Interrupt Generation.
**          - Analog Input Multiplexer for 8 (16)Analog Input Channels.
**          - Analog/Digital Input Pin Multiplexing.
**          - 1 to 8 (1 to 16)Conversion Sequence Lengths.
**          - Continuous Conversion Mode.
**          - Multiple Channel Scans.
**     Settings  :
**          Component name                                 : ADC_Port_AD
**          Device                                         : ADC
**          Settings                                       : 
**            Clock settings                               : 
**              Discharge before sampling                  : no
**              Sample time                                : 4 A/D conversion clock periods
**              Prescaler                                  : 5
**              Frequency                                  : 2083.3 kHz
**              Conversion time                            : 9.1 us
**            Conv. sequence length                        : 4
**            Conversion mode                              : Single conversion
**            Channel sample mode                          : Only one channel
**            Result data formats                          : 10-bit/left justified/unsigned
**            Fast flag clear all                          : Disabled
**            Wrap around channel                          : AN11
**            External trigger                             : Disabled
**            External trigger control                     : Falling edge
**            Conv. results are placed in                  : Corresponding result register
**            Background debug freeze                      : Continue conversion
**            Special channel conversion                   : Disabled
**            Number of automatic comparison               : 0
**          Pins/Signals                                   : 
**            External trigger                             : no
**            ADC input pins                               : 1
**              Input Pin0                                 : 
**                Pin                                      : PAD0_KWAD0_AN0
**                Pin Signal                               : SUPPLY_VOLTAGE
**                Digital Input                            : Disabled
**          Interrupts                                     : 
**            Sequence Complete                            : 
**              Sequence complete interrupt                : Disabled
**              Interrupt                                  : Vatd
**              Priority                                   : 1
**              ISR name                                   : 
**            Compare                                      : 
**              Compare interrupt                          : Disabled
**              Interrupt                                  : Vatdcompare
**              Priority                                   : 1
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Start ADC conversion                         : no
**     Contents  :
**         Init - void ADC_Port_AD_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE ADC_Port_AD. */

#include "ADC_Port_AD.h"

/*
** ===================================================================
**     Method      :  ADC_Port_AD_Init (component Init_ADC)
**
**     Description :
**         This method initializes registers of the ADC module
**         according to this Peripheral Initialization Component settings.
**         Call this method in user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void ADC_Port_AD_Init(void)
{
        
        
  /* Initialization of the ADC module */
  /* ATDCTL0: ??=0,??=0,??=0,??=0,WRAP3=1,WRAP2=1,WRAP1=1,WRAP0=1 */
  setReg8(ATDCTL0, 0x0FU);              
  /* ATDCTL1: ETRIGSEL=0,SRES1=0,SRES0=1,SMP_DIS=0,ETRIGCH3=1,ETRIGCH2=1,ETRIGCH1=1,ETRIGCH0=1 */
  setReg8(ATDCTL1, 0x2FU);              
  /* ATDCTL3: DJM=0,S8C=0,S4C=1,S2C=0,S1C=0,FIFO=0,FRZ1=0,FRZ0=0 */
  setReg8(ATDCTL3, 0x20U);              
  /* ATDCTL4: SMP2=0,SMP1=0,SMP0=0,PRS4=0,PRS3=0,PRS2=1,PRS1=0,PRS0=1 */
  setReg8(ATDCTL4, 0x05U);              
  /* ATDCTL5: ??=0,SC=0,SCAN=0,MULT=0,CD=0,CC=0,CB=0,CA=0 */
  setReg8(ATDCTL5, 0x00U);              
  /* ATDCTL2: ??=0,AFFC=0,??=0,ETRIGLE=0,ETRIGP=0,ETRIGE=0,ASCIE=0,ACMPIE=0 */
  setReg8(ATDCTL2, 0x00U);              
}

/* END ADC_Port_AD. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
