/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Cpu.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : MC9S12G64_32
**     Version   : Component 01.016, Driver 02.06, CPU db: 3.00.020
**     Datasheet : MC9S12GRMV1 Rev. 1.02 June 7, 2011
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 13/07/2022, 16:55
**     Abstract  :
**         This component "MC9S12G64_32" implements properties, methods,
**         and events of the CPU.
**     Settings  :
**
**     Contents  :
**         EnableInt   - void Cpu_EnableInt(void);
**         DisableInt  - void Cpu_DisableInt(void);
**         SetWaitMode - void Cpu_SetWaitMode(void);
**         SetStopMode - void Cpu_SetStopMode(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Cpu. */

#include "CAN1.h"
#include "GPIO_Port_S.h"
#include "GPIO_Port_T.h"
#include "IEE1.h"
#include "SM1.h"
#include "SPI_SS.h"
#include "ADC.h"
#include "ST25_IRQ.h"
#include "Events.h"
#include "Cpu.h"
#include "Timer_1ms.h"

#define CGM_DELAY  0x0CFFU

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT


/* Global variables */
volatile byte CCR_reg;                 /* Current CCR reegister */
#pragma CODE_SEG __NEAR_SEG NON_BANKED


/*
** ===================================================================
**     Method      :  Cpu_Cpu_Interrupt (component MC9S12G64_32)
**
**     Description :
**         The method services unhandled interrupt vectors.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
// ISR(Cpu_Interrupt)
// {/*PT1AD_PT1AD2 ^= 1;*/
//   /*lint -save -e950 Disable MISRA rule (1.1) checking. */
//   asm(BGND);
//   /*lint -restore Enable MISRA rule (1.1) checking. */
// }


#pragma CODE_SEG DEFAULT

/*
** ===================================================================
**     Method      :  Cpu_DisableInt (component MC9S12G64_32)
**
**     Description :
**         Disable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_DisableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_EnableInt (component MC9S12G64_32)
**
**     Description :
**         Enable maskable interrupts
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_EnableInt(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetStopMode (component MC9S12G64_32)
**
**     Description :
**         Set low power mode - Stop mode.
**         For more information about the stop mode see
**         documentation of this CPU.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetStopMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  Cpu_SetWaitMode (component MC9S12G64_32)
**
**     Description :
**         Set low power mode - Wait mode.
**         For more information about the wait mode see
**         documentation of this CPU.
**         Release from Wait mode: Reset or interrupt
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Cpu_SetWaitMode(void)

**      This method is implemented as macro in the header module. **
*/

/*
** ===================================================================
**     Method      :  _EntryPoint (component MC9S12G64_32)
**
**     Description :
**         Initializes the whole system like timing and so on. At the end 
**         of this function, the C startup is invoked to initialize stack,
**         memory areas and so on.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
extern void _Startup(void);            /* Forward declaration of external startup function declared in file Start12.c */

/*** !!! Here you can place your own code using property "User data declarations" on the build options tab of the CPU component. !!! ***/


#pragma CODE_SEG __NEAR_SEG NON_BANKED


#pragma NO_FRAME                       /* Suppress generation of frame code */
#pragma NO_EXIT                        /* Suppress generation of exit from a function */
void _EntryPoint(void)
{

  /*** !!! Here you can place your own code using property "User code before PE initialization" on the build options tab of the CPU compoennt. !!! ***/

  /* ### MC9S12G64_32 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* MMCCTL1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,NVMRES=0 */
  setReg8(MMCCTL1, 0x00U);              
  /* PKGCR: APICLKS7=0,??=0,??=0,??=0,??=0,PKGCR2=0,PKGCR1=0,PKGCR0=1 */
  setReg8(PKGCR, 0x01U);                
  /* DIRECT: DP15=0,DP14=0,DP13=0,DP12=0,DP11=0,DP10=0,DP9=0,DP8=0 */
  setReg8(DIRECT, 0x00U);               
  /* IVBR: IVB_ADDR=0xFF */
  setReg8(IVBR, 0xDEU);                 
  /* ECLKCTL: NECLK=1,NCLKX2=1,DIV16=0,EDIV4=0,EDIV3=0,EDIV2=0,EDIV1=0,EDIV0=0 */
  setReg8(ECLKCTL, 0xC0U);              
  /*  System clock initialization */
  /* CPMUPROT: ??=0,??=0,??=1,??=0,??=0,??=1,??=1,PROT=0 */
  setReg8(CPMUPROT, 0x26U);            /* Disable protection of clock configuration registers */ 
  /* CPMUCLKS: PSTP=0 */
  clrReg8Bits(CPMUCLKS, 0x40U);         
  /* CPMUCLKS: PLLSEL=1 */
  setReg8Bits(CPMUCLKS, 0x80U);        /* Enable the PLL to allow write to divider registers */ 
  /* CPMUREFDIV: REFFRQ1=0,REFFRQ0=0,??=0,??=0,REFDIV3=1,REFDIV2=1,REFDIV1=1,REFDIV0=1 */
  setReg8(CPMUREFDIV, 0x0FU);          /* Set the divider register */ 
  /* CPMUSYNR: VCOFRQ1=0,VCOFRQ0=1,SYNDIV5=0,SYNDIV4=1,SYNDIV3=1,SYNDIV2=0,SYNDIV1=0,SYNDIV0=0 */
  setReg8(CPMUSYNR, 0x58U);            /* Set the multiplier register */ 
  /* CPMUPOSTDIV: ??=0,??=0,??=0,POSTDIV4=0,POSTDIV3=0,POSTDIV2=0,POSTDIV1=0,POSTDIV0=0 */
  setReg8(CPMUPOSTDIV, 0x00U);         /* Set the post divider register */ 
  /* CPMUOSC: OSCE=1,??=0,OSCPINS_EN=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(CPMUOSC, 0x80U);             /* Enable the oscillator */ 
  /* CPMUPLL: ??=0,??=0,FM1=0,FM0=0,??=0,??=0,??=0,??=0 */
  setReg8(CPMUPLL, 0x00U);             /* Set the PLL frequency modulation */ 
  while(CPMUFLG_UPOSC == 0U) {         /* Wait until the oscillator is qualified by the PLL */
  }
  /* CPMUPROT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,PROT=0 */
  setReg8(CPMUPROT, 0x00U);            /* Enable protection of clock configuration registers */ 
  /* CPMUCOP: RSBCK=0,WRTMASK=0 */
  clrReg8Bits(CPMUCOP, 0x60U);          
  /*** End of PE initialization code after reset ***/

  /*** !!! Here you can place your own code using property "User code after PE initialization" on the build options tab of the CPU component. !!! ***/

  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  __asm("jmp _Startup");               /* Jump to C startup code */
  /*lint -restore Enable MISRA rule (1.1) checking. */
}

#pragma CODE_SEG DEFAULT
/*
** ===================================================================
**     Method      :  PE_low_level_init (component MC9S12G64_32)
**
**     Description :
**         Initializes components and provides common register 
**         initialization. The method is called automatically as a part 
**         of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void PE_low_level_init(void)
{
  /* Common initialization of the CPU registers */
  /* DDRS: DDRS6=1,DDRS5=1,DDRS4=0 */
  clrSetReg8Bits(DDRS, 0x10U, 0x60U);   
  /* PTS: PTS6=0 */
  clrReg8Bits(PTS, 0x40U);              
  /* PIEP: PIEP1=0 */
  clrReg8Bits(PIEP, 0x02U);             
  /* PTP: PTP1=1 */
  clrReg8Bits(PTP, 0x02U);//setReg8Bits(PTP, 0x02U);              
  /* PERP: PERP1=1 -> Pull enabled */
  setReg8Bits(PERP, 0x02U);//clrReg8Bits(PERP, 0x02U); 
  /* PPSP: PPSP1=1 -> PullDOWN */
  setReg8Bits(PPSP, 0x02U);            
  /* DDRP: DDRP1=1 */
  setReg8Bits(DDRP, 0x02U);             
  /* PER1AD: PER1AD6=0 */
  setReg8Bits(PER1AD, 0x40U);//PEx: clrReg8Bits(PER1AD, 0x40U);           
  /* DDR1AD: DDR1AD6=0 */
  clrReg8Bits(DDR1AD, 0x40U); /*1:Output -- 0:Input*/           
  /* ACMPC: ACDIEN=1 */
  setReg8Bits(ACMPC, 0x10U); 
    /* TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=1,??=0,??=0,??=0 */
  setReg8(TSCR1, 0x08U);                
  /* OCPD: OCPD0=1 */
  setReg8Bits(OCPD, 0x01U);             
  /* TIOS: IOS0=1 */
  setReg8Bits(TIOS, 0x01U);             
  /* TCTL2: OM0=0,OL0=0 */
  clrReg8Bits(TCTL2, 0x03U);            
  /* TTOV: TOV0=0 */
  clrReg8Bits(TTOV, 0x01U);             
  /* TSCR2: TOI=0 */
  clrReg8Bits(TSCR2, 0x80U);            
  /* TFLG1: ??=1,??=1,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  setReg8(TFLG1, 0xFFU);                
  /* TIE: C0I=1 */
  setReg8Bits(TIE, 0x01U);              
  /* PTPSR: PTPS7=0,PTPS6=0,PTPS5=0,PTPS4=0,PTPS3=0,PTPS2=0,PTPS1=0,PTPS0=0 */
  setReg8(PTPSR, 0x00U);            
  /* CPMUINT: LOCKIE=0,OSCIE=0 */
  clrReg8Bits(CPMUINT, 0x92U);    //0x12      
  /* CPMULVCTL: LVIE=0 */
  clrReg8Bits(CPMULVCTL, 0x02U);        
  /* IRQCR: IRQEN=0 */
  clrReg8Bits(IRQCR, 0x40U);            
  /* ATDDIEN: IEN6=1,IEN0=0 */
  clrSetReg16Bits(ATDDIEN, 0x01U, 0x40U); 
  /* PPS01AD: PPS1AD6=1 */
  setReg8Bits(PPS1AD, 0x40U);         
  /* ### MC9S12G64_32 "Cpu" init code ... */
  /* ### Init_MSCAN "CAN1" init code ... */
  CAN1_Init();
  /* ### Init_GPIO "GPIO_Port_S" init code ... */
  GPIO_Port_S_Init();
  /* ### Init_GPIO "GPIO_Port_T" init code ... */
  GPIO_Port_T_Init();
  /* ### IntEEPROM "IEE1" init code ... */
  IEE1_Init();
  /* ###  Synchro master "SM1" init code ... */
  SM1_Init();
  /* ### BitIO "SPI_SS" init code ... */
  /* ###  "ADC" init code ... */
  ADC_Init();
  /* ### External interrupt "ST25_IRQ" init code ... */
  PIF1AD = 0x40U;                      /* Clear flag */ //The FK issue
  PIE1AD_PIE1AD6 = 1U;                /* Enable interrupt */ //The FK issue

/* ### TimerInt "Timer_1ms" init code ... */
  
  
  /* TC0: BIT15=0,BIT14=1,BIT13=1,BIT12=0,BIT11=0,BIT10=0,BIT9=0,BIT8=1,BIT7=1,BIT6=0,BIT5=1,BIT4=0,BIT3=1,BIT2=0,BIT1=0,BIT0=0 */
  setReg16(TC0, 0x61A8U);              /* Store given value to the compare register */ 
  /* Common peripheral initialization - ENABLE */
  /* TSCR1: TEN=1,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=1,??=0,??=0,??=0 */
  setReg8(TSCR1, 0x88U);

  /*Enable Debug Pins*/
  setReg8Bits(DDR1AD, 0x06U); /*1:Output -- 0:Input*/ 
  setReg8Bits(PPS1AD, 0x06U);
  setReg8Bits(PER1AD, 0x06U);
  
  __EI();                              /* Enable interrupts */
}

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/*lint -restore Enable MISRA rule (1.1) checking. */

/* END Cpu. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
