/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO_Port_S.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.07, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 12/07/2022, 20:44
**     Abstract  :
**          This file implements the General Purpose Input Output (S)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO_Port_S
**          Device                                         : S
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       7             |  PS7_API_EXTCLK_ECLK_PWM5_SS0
**             ----------------------------------------------------
**
**          Pin7                                           : PS7_API_EXTCLK_ECLK_PWM5_SS0
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO_Port_S_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIO_Port_S. */

#include "GPIO_Port_S.h"
/*
** ===================================================================
**     Method      :  GPIO_Port_S_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIO_Port_S_Init(void)
{
  /* PTS: PTS7=1 */
  setReg8Bits(PTS, 0x80U);              
  /* PPSS: PPSS7=1 */
  setReg8Bits(PPSS, 0x80U);             
  /* WOMS: WOMS7=0 */
  clrReg8Bits(WOMS, 0x80U);             
  /* PERS: PERS7=1 */
  setReg8Bits(PERS, 0x80U);             
  /* DDRS: DDRS7=1 */
  setReg8Bits(DDRS, 0x80U);             
}

/* END GPIO_Port_S. */

void CAN_STB_MODE(CAN_STB_MODE_t Mode)
{
  if(Mode == STANDBY)
  {
    /*StadBy*/
    PTS_PTS7 = 1;
  }
  else
  {
    /*Normal*/
    PTS_PTS7 = 0;
  }
}

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
