/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO_Port_T.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.07, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 17/09/2021, 18:00
**     Abstract  :
**          This file implements the General Purpose Input Output (T)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO_Port_T
**          Device                                         : T
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PT0_IOC0_XIRQ
**                       1             |  PT1_IOC1_IRQ
**                       2             |  PT2_IOC2
**                       3             |  PT3_IOC3
**             ----------------------------------------------------
**
**          Pin0                                           : PT0_IOC0_XIRQ
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin1                                           : PT1_IOC1_IRQ
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PT2_IOC2
**            Direction                                    : Output
**            Output value                                 : 0
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin3                                           : PT3_IOC3
**            Direction                                    : Output
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO_Port_T_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __GPIO_Port_T
#define __GPIO_Port_T

/* MODULE GPIO_Port_T. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void GPIO_Port_T_Init(void);
/*
** ===================================================================
**     Method      :  GPIO_Port_T_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END GPIO_Port_T. */
#endif /* ifndef __GPIO_Port_T */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
