/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO_Port_S.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.07, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 17/09/2021, 15:43
**     Abstract  :
**          This file implements the General Purpose Input Output (S)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO_Port_S
**          Device                                         : S
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       0             |  PS0_RXD0
**                       1             |  PS1_TXD0
**                       4             |  PS4_PWM4_MISO0
**                       5             |  PS5_IOC4_MOSI0
**                       6             |  PS6_IOC5_SCK0
**                       7             |  PS7_API_EXTCLK_ECLK_PWM5_SS0
**             ----------------------------------------------------
**
**          Pin0                                           : PS0_RXD0
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin1                                           : PS1_TXD0
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Pin4                                           : PS4_PWM4_MISO0
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : pull up
**            Open drain                                   : push-pull
**
**          Pin5                                           : PS5_IOC4_MOSI0
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : pull up
**            Open drain                                   : push-pull
**
**          Pin6                                           : PS6_IOC5_SCK0
**            Direction                                    : Input
**            Output value                                 : 0
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin7                                           : PS7_API_EXTCLK_ECLK_PWM5_SS0
**            Direction                                    : Output
**            Output value                                 : 1
**            Pull resistor                                : pull down
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO_Port_S_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIO_Port_S. */

#include "GPIO_Port_S.h"
/*
** ===================================================================
**     Method      :  GPIO_Port_S_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIO_Port_S_Init(void)
{
  /* PTS: PTS7=1,PTS6=0 */
  clrSetReg8Bits(PTS, 0x40U, 0x80U);    
  /* PPSS: PPSS7=1,PPSS5=0,PPSS4=0,PPSS1=1,PPSS0=1 */
  clrSetReg8Bits(PPSS, 0x30U, 0x83U);   
  /* WOMS: WOMS7=0,WOMS6=0,WOMS5=0,WOMS4=0,WOMS1=0,WOMS0=0 */
  clrReg8Bits(WOMS, 0xF3U);             
  /* PERS: PERS7=1,PERS5=1,PERS4=1,PERS1=1,PERS0=1 */
  setReg8Bits(PERS, 0xB3U);             
  /* DDRS: DDRS7=1,DDRS6=0,DDRS5=0,DDRS4=0,DDRS1=0,DDRS0=0 */
  clrSetReg8Bits(DDRS, 0x73U, 0x80U);   
}

/* END GPIO_Port_S. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
