/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO_Port_AD.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.07, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 12/07/2022, 20:44
**     Abstract  :
**          This file implements the General Purpose Input Output (ADL)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO_Port_AD
**          Device                                         : ADL
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       1             |  PAD1_KWAD1_AN1
**                       2             |  PAD2_KWAD2_AN2
**                       6             |  PAD6_KWAD6_AN6_ACMPP
**             ----------------------------------------------------
**
**          Pin1                                           : PAD1_KWAD1_AN1
**            Direction                                    : Output
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PAD2_KWAD2_AN2
**            Direction                                    : Output
**            Output value                                 : no initialization
**            Pull resistor                                : pull up
**            Open drain                                   : push-pull
**
**          Pin6                                           : PAD6_KWAD6_AN6_ACMPP
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO_Port_AD_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE GPIO_Port_AD. */

#include "GPIO_Port_AD.h"
/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      Generic_Latch_Bootloader.c
**      Events.c
**
** ###################################################################
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(ST25_IRQ_OnInterrupt)
        {
        // NOTE: The routine should include the following actions to obtain
        //       correct functionality of the hardware.
        //
        //      To clear interrupt flag 1 must be written to a bit, which correspods
        //      to pin which detected an active edge.
        //      Example: PIF01AD = 0xFF;
        }
#pragma CODE_SEG DEFAULT


/*
** ===================================================================
**     Method      :  GPIO_Port_AD_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void GPIO_Port_AD_Init(void)
{
    /* Disable interrupts */
  /* PIE1AD: PIE1AD7=0,PIE1AD6=0,PIE1AD5=0,PIE1AD4=0,PIE1AD3=0,PIE1AD2=0,PIE1AD1=0,PIE1AD0=0 */
  setReg8(PIE1AD, 0x00U);               
    /* Clear interrupt flags */
  /* PIF1AD: PIF1AD7=1,PIF1AD6=1,PIF1AD5=1,PIF1AD4=1,PIF1AD3=1,PIF1AD2=1,PIF1AD1=1,PIF1AD0=1 */
  setReg8(PIF1AD, 0xFFU);               
  /* PPS1AD: PPS1AD2=0 */
  clrReg8Bits(PPS1AD, 0x04U);           
  /* PER1AD: PER1AD6=0,PER1AD2=1 */
  clrSetReg8Bits(PER1AD, 0x40U, 0x04U); 
  /* DDR1AD: DDR1AD6=0,DDR1AD2=1,DDR1AD1=1 */
  clrSetReg8Bits(DDR1AD, 0x40U, 0x06U); 
  /* PIE1AD: PIE1AD7=0,PIE1AD6=1,PIE1AD5=0,PIE1AD4=0,PIE1AD3=0,PIE1AD2=0,PIE1AD1=0,PIE1AD0=0 */
  setReg8(PIE1AD, 0x40U);               
}

/* END GPIO_Port_AD. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
