/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : GPIO_Port_AD.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_GPIO
**     Version   : Component 01.114, Driver 01.07, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 12/07/2022, 20:44
**     Abstract  :
**          This file implements the General Purpose Input Output (ADL)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**
**     Settings  :
**          Component name                                 : GPIO_Port_AD
**          Device                                         : ADL
**          Port control                                   : Individual pins
**
**          Used pins                                      :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       1             |  PAD1_KWAD1_AN1
**                       2             |  PAD2_KWAD2_AN2
**                       6             |  PAD6_KWAD6_AN6_ACMPP
**             ----------------------------------------------------
**
**          Pin1                                           : PAD1_KWAD1_AN1
**            Direction                                    : Output
**            Output value                                 : no initialization
**            Pull resistor                                : no initialization
**            Open drain                                   : push-pull
**
**          Pin2                                           : PAD2_KWAD2_AN2
**            Direction                                    : Output
**            Output value                                 : no initialization
**            Pull resistor                                : pull up
**            Open drain                                   : push-pull
**
**          Pin6                                           : PAD6_KWAD6_AN6_ACMPP
**            Direction                                    : Input
**            Output value                                 : no initialization
**            Pull resistor                                : no pull resistor
**            Open drain                                   : push-pull
**
**          Call Init method                               : yes
**     Contents  :
**         Init - void GPIO_Port_AD_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __GPIO_Port_AD
#define __GPIO_Port_AD

/* MODULE GPIO_Port_AD. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void GPIO_Port_AD_Init(void);
/*
** ===================================================================
**     Method      :  GPIO_Port_AD_Init (component Init_GPIO)
**
**     Description :
**         This method initializes registers of the GPIO module
**         according to this Peripheral Initialization settings. Call
**         this method in the user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see GPIO_Port_AD.c file for more information).
** ===================================================================
*/
#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void ST25_IRQ_OnInterrupt(void);
#pragma CODE_SEG DEFAULT

/* END GPIO_Port_AD. */
#endif /* ifndef __GPIO_Port_AD */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
