/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : IEE1.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : IntEEPROM
**     Version   : Component 02.200, Driver 01.25, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 29/07/2021, 17:49
**     Abstract  :
**         This device "IntEEPROM" implements internal EEPROM
**     Comment   :
**         The EEPROM array is organized as rows of word (2 bytes), the EEPROM block's
**         erase sector size is 2 rows (2 words). Therefore it is preferable
**         to use word aligned data for writting - methods SetWord and SetLong -
**         with word aligned address.
**         Driver expects that all security options of EEPROM are disabled.
**         If some security option is enabled methods performing write
**         operation (such as SetWord) can return error.
**     Settings  :
**         EEPROM size                 : 1536 byte
**         Initialization:
**              Wait in methods        : Enabled
**              EEPROM clock           : High: 1000 kHz
**
**     Contents  :
**         SetByte     - byte IEE1_SetByte(IEE1_TAddress Addr, byte Data);
**         GetByte     - byte IEE1_GetByte(IEE1_TAddress Addr, byte *Data);
**         SetWord     - byte IEE1_SetWord(IEE1_TAddress Addr, word Data);
**         GetWord     - byte IEE1_GetWord(IEE1_TAddress Addr, word *Data);
**         SetLong     - byte IEE1_SetLong(IEE1_TAddress Addr, dword Data);
**         GetLong     - byte IEE1_GetLong(IEE1_TAddress Addr, dword *Data);
**         SetActByte  - byte IEE1_SetActByte(byte Data);
**         GetActByte  - byte IEE1_GetActByte(byte *Data);
**         SetWait     - void IEE1_SetWait(bool Wait);
**         Busy        - bool IEE1_Busy(void);
**         EraseSector - byte IEE1_EraseSector(IEE1_TAddress Addr);
**         EraseEeprom - byte IEE1_EraseEeprom(IEE1_TAddress Addr);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE IEE1. */

#include "IEE1.h"

/* Internal type for addressing of the EEPROM. */
typedef const far word * far IEE1_TAddress_; /* Type of address to the EEPROM */

#pragma DATA_SEG IEE1_DATA             /* Select data segment "IEE1_DATA" */
#pragma CODE_SEG IEE1_CODE

#pragma MESSAGE DISABLE C12056         /* Disable warning C12056 "SP debug info incorrect becouse of optimization or inline assembler" */
/*lint -save  -e923 -e926 -e927 -e928 -e929 Disable MISRA rule (11.3,11.4) checking. */

bool IEE1_Wait;                        /* Wait status of writting methods */
static IEE1_TAddress EEPROMaddr;       /* Address of EEPROM which will be programmed/read */
static word BackupArray[0x02];         /* Array for backup data from erased sector */

/*
** ===================================================================
**     Method      :  GlobalToLocal (component IntEEPROM)
**
**     Description :
**         The macro converts global address to local (banked) address.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define GlobalToLocal(Address) ((((dword)Address) & 0x3FFFU) | ((((dword)Address) & 0x003FC000UL) << 2) | 0x8000U)



/*
** ===================================================================
**     Method      :  BackupSector (component IntEEPROM)
**
**     Description :
**         The method backups the content of a sector being erased.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void BackupSector(IEE1_TAddress_ Addr, word From, word To)
{
  word i;

  for (i = From; i < To; i = i + 2U) {
    BackupArray[i/2U] = *(word *far) (((word *far)GlobalToLocal(Addr)) + (i/2U)); /* save one sector to RAM */
  }
}

/*
** ===================================================================
**     Method      :  WriteBlock (component IntEEPROM)
**
**     Description :
**         The method writes the block of data to EEPROM memory.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte WriteBlock(IEE1_TAddress Addr, word From, word To, const word* Data)
{
  byte err = 0U;
  word i;
  byte j;
  dword PhraseAddr;

  if(From == To) {
    return ERR_OK;
  }
  i = From;
  PhraseAddr = (dword)Addr;
  while(i < To) {
  /* FSTAT: ACCERR=1,FPVIOL=1 */
    FSTAT = 0x30U;                     /* Clear error flags */
    FCCOBIX = 0U;                      /* Clear index register */
    FCCOBHI = 0x11U;                   /* Program D-Flash command */
    FCCOBLO = (byte)(PhraseAddr >> 16U); /* High address word */
    FCCOBIX++;                         /* Shift index register */
    FCCOB = (word)PhraseAddr;          /* Low address word */
    for(j = 0U;j < 8U;j+=2U) {
      FCCOBIX++;                       /* Shift index register */
      FCCOB = *(const word*)(Data + (i/2U)); /* Load new data */
      i += 2U;
      if(i >= To) {break;}
    }
    FSTAT = 0x80U;                     /* Clear flag command buffer empty */
    if (i < To) {                      /* Write not last word */
      while (FSTAT_CCIF == 0U) {}      /* Wait to command complete */
      if ((FSTAT & 0x30U) != 0U) {     /* Is protection violation or acces error detected ? */
        return ERR_NOTAVAIL;           /* If yes then error */
      }
      if (FSTAT_MGSTAT) {              /* Was attempt to write data to the given address errorneous? */
        err = 1U;                      /* If yes then mark an error */
      }
    }
    PhraseAddr += 8U;
  }
  if (IEE1_Wait) {                     /* Is the flag set ? */
    while (FSTAT_CCIF == 0U) {}        /* Wait for command completition */
    if ((FSTAT & 0x30U) != 0U) {       /* Is protection violation or acces error detected ? */
      return ERR_NOTAVAIL;             /* If yes then error */
    }
    if (FSTAT_MGSTAT) {                /* Was attempt to write data to the given address errorneous? */
      err = 1U;                        /* If yes then mark an error */
    }
  }
  if(err != 0U) {
    return ERR_VALUE;                  /* If yes then error */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  EraseSectorInternal (component IntEEPROM)
**
**     Description :
**         The method erase a specific sector.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte EraseSectorInternal(IEE1_TAddress Addr)
{
  if (FSTAT_CCIF == 0U) {              /* Is command complete ? */
    return ERR_BUSY;                   /* If yes then error */
  }
  /* FSTAT: ACCERR=1,FPVIOL=1 */
  FSTAT = 0x30U;                       /* Clear error flags */
  FCCOBIX = 0U;                        /* Clear index register */
  FCCOBHI = 0x12U;                     /* Erase D-Flash sector command */
  FCCOBLO = (byte)(((dword)Addr) >> 16); /* High address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = (word)(((dword)Addr) & 0xFFFFFFFEUL); /* Low address word aligned to word*/
  FSTAT = 0x80U;                       /* Clear flag command buffer empty */
  while (FSTAT_CCIF == 0U) {}          /* Wait to command complete */
  if ((FSTAT & 0x23U) != 0U) {         /* Is access error or other error detected ? */
    return ERR_NOTAVAIL;               /* If yes then error */
  }
  return ERR_OK;                       /* OK */
}
/*
** ===================================================================
**     Method      :  WriteWord (component IntEEPROM)
**
**     Description :
**         The method writes the word data to EEPROM memory.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static byte WriteWord(IEE1_TAddress AddrRow,word Data16)
{
  if (FSTAT_CCIF == 0U) {              /* Is previous command in process ? */
    return ERR_BUSY;                   /* If yes then error */
  }
  /* FSTAT: ACCERR=1,FPVIOL=1 */
  FSTAT = 0x30U;                       /* Clear error flags */
  FCCOBIX = 0U;                        /* Clear index register */
  FCCOBHI = 0x11U;                     /* Program D-Flash command */
  FCCOBLO = (byte)(((dword)AddrRow) >> 16); /* High address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = (word)((dword)AddrRow);      /* Low address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = Data16;                      /* Load new data */
  FSTAT = 0x80U;                       /* Clear flag command complete */
  if ((FSTAT & 0x30U) != 0U) {         /* Is protection violation or acces error detected ? */
    return ERR_NOTAVAIL;               /* If yes then error */
  }
  if (IEE1_Wait) {                     /* Is the flag set ? */
    while (!FSTAT_CCIF) {}             /* If yes then wait for command completition */
    if (FSTAT_MGSTAT) {                /* Was attempt to write data to the given address errorneous? */
      return ERR_VALUE;                /* If yes then error */
    }
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  IEE1_SetByte (component IntEEPROM)
**
**     Description :
**         This method writes a given byte to a specified address in
**         EEPROM. The method also sets address pointer for <SetActByte>
**         and <GetActByte> methods (applicable only if these methods
**         are enabled). The pointer is set to address passed as the
**         parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - parameter Addr is out of range
** ===================================================================
*/
byte IEE1_SetByte(IEE1_TAddress Addr,byte Data)
{
  byte err;
  word Data16;
  IEE1_TAddress SecAddr;               /* EEPROM Sector address */

  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = Addr;                   /* Store given address */
  SecAddr = (IEE1_TAddress)((dword)Addr & 0x00FFFFFEUL); /* Aligned word address */
  if (*((word *far)GlobalToLocal(SecAddr)) == 0xFFFFU) { /* Is the word erased? */
    if (((dword)Addr) & 1U) {          /* Not Aligned word ? */
      return(WriteWord(SecAddr, ((*((word *far)GlobalToLocal(SecAddr)) & 0xFF00U) | Data)));
    } else {
      return(WriteWord(Addr, (((word)Data << 8) | (*(((byte *far)GlobalToLocal(Addr)) + 1U))))); /* Aligned word ? */
    }
  } else {                             /* Is given address non-erased ? */
    SecAddr = (IEE1_TAddress)((dword)Addr & 0x00FFFFFCUL); /* Sector Aligned address */
    BackupSector(SecAddr, 0U, 0x04U);  /* Backup sector */
    Data16 = BackupArray[(((dword)Addr) % 0x04U) / 2U]; /* Store new data to backup array*/
    if (((dword)Addr) & 1U) {          /* Not Aligned word ? */
      Data16 = (Data16 & 0xFF00U) | Data;
    } else {
      Data16 = ((word)Data << 8) | (Data16 & 0xFFU);
    }
    BackupArray[(((dword)Addr) % 0x04U) / 2U] = Data16; /* Write new data to saved sector */
    err = EraseSectorInternal(Addr);   /* Erase sector */
    if(err != 0U) {
      return(err);                     /* Return error code if previous operation finished not correctly */
    }
    err = WriteBlock(SecAddr, 0U, 0x04U,BackupArray); /* Restore sector */
    return(err);
  }
}

/*
** ===================================================================
**     Method      :  IEE1_GetByte (component IntEEPROM)
**
**     Description :
**         This method reads a byte from a specified EEPROM address.
**         The method also sets address pointer for <SetActByte> and
**         <GetActByte> methods (applicable only if these methods are
**         enabled). The pointer is set to address passed as the
**         parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - EEPROM Address
**       * Data            - A pointer to the returned 8-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - parameter Addr is out of range
** ===================================================================
*/
byte IEE1_GetByte(IEE1_TAddress Addr,byte *Data)
{
  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = Addr;                   /* Store given address */
  *Data = *((byte *far)GlobalToLocal(Addr));
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IEE1_SetWord (component IntEEPROM)
**
**     Description :
**         This method writes a given word (2 bytes) to the specified
**         address in EEPROM. The method also sets address pointer for
**         <SetActByte> and <GetActByte> methods (applicable only if
**         these methods are enabled). The pointer is set to address
**         passed as the parameter + 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/
byte IEE1_SetWord(IEE1_TAddress Addr,word Data)
{
  byte err;
  IEE1_TAddress SecAddr;               /* EEPROM Sector address */

  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if ((dword)Addr & 0x01U) {           /* Aligned address ? */
    return ERR_NOTAVAIL;
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = (IEE1_TAddress)((dword)(Addr) + 1U); /* Store given address */
  if (*((word *far)GlobalToLocal(Addr)) == 0xFFFFU) { /* Is the word erased? */
      return(WriteWord(Addr, Data));
  } else {                             /* Is given address non-erased ? */
    SecAddr = (IEE1_TAddress)((dword)Addr & 0x00FFFFFCUL); /* Sector Aligned address */
    BackupSector(SecAddr, 0U, 0x04U);  /* Backup sector */
    BackupArray[(((dword)Addr) % 0x04U) / 2U] = Data; /* Write new data to saved sector */
    err = EraseSectorInternal(Addr);   /* Erase sector */
    if(err != 0U) {
      return(err);                     /* Return error code if previous operation finished not correctly */
    }
    err = WriteBlock(SecAddr, 0U, 0x04U,BackupArray); /* Restore sector */
    return(err);
  }
}

/*
** ===================================================================
**     Method      :  IEE1_GetWord (component IntEEPROM)
**
**     Description :
**         This method reads a word (2 bytes) from the specified EEPROM
**         address. The method also sets address pointer for
**         <SetActByte> and <GetActByte> methods (applicable only if
**         these methods are enabled). The pointer is set to address
**         passed as the parameter + 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**       * Data            - Pointer to returned 16-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/
byte IEE1_GetWord(IEE1_TAddress Addr,word *Data)
{
  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = (IEE1_TAddress)((dword)(Addr) + 1U); /* Store given address */
  *Data = *((word *far)GlobalToLocal(Addr)); /* Return data from given address */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IEE1_SetLong (component IntEEPROM)
**
**     Description :
**         This method writes a given long word (4 bytes) to the
**         specified address in EEPROM. The method also sets address
**         pointer for <SetActByte> and <GetActByte> methods
**         (applicable only if these methods are enabled). The pointer
**         is set to address passed as the parameter + 3.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/
byte IEE1_SetLong(IEE1_TAddress Addr,dword Data)
{
  byte err;
  IEE1_TAddress SecAddr;               /* EEPROM Sector address */

  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if ((dword)Addr & 0x03U) {           /* Aligned address ? */
    return ERR_NOTAVAIL;
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = (IEE1_TAddress)((dword)(Addr) + 3U); /* Store given address */
  if (*((dword *far)GlobalToLocal(Addr)) == 0xFFFFFFFFUL) { /* Is the dword erased? */
    err = WriteBlock(Addr, 0U, 0x04U,((word*)&Data)); /* Write dword */
  } else {                             /* Is given address non-erased ? */
    SecAddr = (IEE1_TAddress)((dword)Addr & 0x00FFFFFCUL); /* Sector Aligned address */
    BackupSector(SecAddr, 0U, 0x04U);  /* Backup sector */
    BackupArray[(((dword)Addr) % 0x04U) / 2U] = (word)(Data >> 16); /* Write new data to saved sector */
    BackupArray[((((dword)Addr) % 0x04U) / 2U) + 1U] = (word)(Data); /* Write new data to saved sector */
    err = EraseSectorInternal(Addr);   /* Erase sector */
    if(err != 0U) {
      return(err);                     /* Return error code if previous operation finished not correctly */
    }
    err = WriteBlock(SecAddr, 0U, 0x04U,BackupArray); /* Restore sector */
  }
  return(err);
}

/*
** ===================================================================
**     Method      :  IEE1_GetLong (component IntEEPROM)
**
**     Description :
**         This method reads a long word (4 bytes) from the specified
**         EEPROM address. The method also sets address pointer for
**         <SetActByte> and <GetActByte> methods (applicable only if
**         these methods are enabled). The pointer is set to address
**         passed as the parameter + 3.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**       * Data            - A pointer to the returned 32-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/
byte IEE1_GetLong(IEE1_TAddress Addr,dword *Data)
{
  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = (IEE1_TAddress)((dword)(Addr) + 3U); /* Store given address */
  *Data = *(far dword *far)(GlobalToLocal(Addr)); /* Return data from given address */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IEE1_SetActByte (component IntEEPROM)
**
**     Description :
**         This method writes given byte to the current address + 1
**         (The EEPROM address is pre-incremented) in EEPROM. The
**         address pointer is set by the methods using address as a
**         parameter, such as _/<GetByte>, <SetByte>/_,etc. - see help
**         of a specific method. Methods _/<GetPage>, <SetPage>/_ set
**         this pointer to the last address of the page.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - current address pointer is
**                           out of range
** ===================================================================
*/
byte IEE1_SetActByte(byte Data)
{
  IEE1_TAddress SecAddr;
  byte err;
  word Data16;

  if ((dword)(EEPROMaddr) > ((dword)(IEE1_AREA_END) - 1U)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = (IEE1_TAddress)((dword)(EEPROMaddr) + 1U); /* Set EEPROM address to the successive byte */
  if (*((word *far)GlobalToLocal(EEPROMaddr)) == 0xFFFFU) { /* Is the word erased? */
    SecAddr = (IEE1_TAddress)((dword)EEPROMaddr & 0x00FFFFFEUL); /* Aligned word address */
    if (((dword)EEPROMaddr) & 1U) {    /* Not Aligned word */
      return(WriteWord(SecAddr, ((*(IEE1_TAddress)GlobalToLocal(SecAddr)) & 0xFF00U) | Data));
    } else {
      return(WriteWord(EEPROMaddr, ((word)Data << 8) | (*(((byte *far)GlobalToLocal(EEPROMaddr)) + 1U)))); /* Aligned word */
    }
  } else {                             /* Is given address non-erased ? */
    SecAddr = (IEE1_TAddress)((dword)EEPROMaddr & 0x00FFFFFCUL); /* Sector Aligned address */
    BackupSector(SecAddr, 0U, 0x04U);  /* Backup sector */
    Data16 = BackupArray[(((dword)EEPROMaddr) % 0x04U) / 2U]; /* Store new data to backup array*/
    if (((dword)EEPROMaddr) & 1U) {    /* Not Aligned word ? */
      Data16 = (Data16 & 0xFF00U) | Data;
    } else {
      Data16 = ((word)Data << 8) | (Data16 & 0xFFU);
    }
    BackupArray[(((dword)EEPROMaddr) % 0x04U) / 2U] = Data16; /* Write new data to saved sector */
    err = EraseSectorInternal(EEPROMaddr); /* Erase sector */
    if(err != 0U) {
      return(err);                     /* Return error code if previous operation finished not correctly */
    }
    err = WriteBlock(SecAddr, 0U, 0x04U,BackupArray); /* Restore sector */
    return(err);
  }
}

/*
** ===================================================================
**     Method      :  IEE1_GetActByte (component IntEEPROM)
**
**     Description :
**         This method reads the current byte +1 (address is
**         pre-incremented) from EEPROM.
**         The address pointer is set by the methods using address as a
**         parameter, such as _/<GetByte>, <SetByte>/_, etc. - see help
**         of a specific method._/<GetPage>, <SetPage>/_ set this
**         pointer to the last address of the page.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Data            - A pointer to the returned 8-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - current address pointer is
**                           out of range
** ===================================================================
*/
byte IEE1_GetActByte(byte *Data)
{
  if ((dword)EEPROMaddr > ((dword)IEE1_AREA_END - 1U)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = (IEE1_TAddress)((dword)EEPROMaddr + 1U); /* Set EEPROM address to the successive byte */
  *Data = *((byte *far)GlobalToLocal(EEPROMaddr));
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  IEE1_SetWait (component IntEEPROM)
**
**     Description :
**         This method changes the wait behavior of all writing methods.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Wait            - 
**                           <true> - methods wait till EEPROM write
**                           operation is finished, data is verified at
**                           the end of writing method
**                           <false> - methods do not wait for the end
**                           of EEPROM write operation, data is not
**                           verified at the end of writing method.
**     Returns     : Nothing
** ===================================================================
*/
/*
void IEE1_SetWait(bool Wait)

**      This method is implemented as macro. See IEE1.h file.      **
*/

/*
** ===================================================================
**     Method      :  IEE1_Busy (component IntEEPROM)
**
**     Description :
**         Method returns the status of EEPROM device.
**     Parameters  : None
**     Returns     :
**         ---             -   - <true> if EEPROM is busy 
**                           - <false> if EEPROM is ready
** ===================================================================
*/
/*
bool IEE1_Busy(void)

**      This method is implemented as macro. See IEE1.h file.      **
*/

/*
** ===================================================================
**     Method      :  IEE1_EraseSector (component IntEEPROM)
**
**     Description :
**         This method erases the smallest erasable area (sector) of
**         the EEPROM determined by given address. The method also sets
**         address pointer for <SetActByte> and <GetActByte> methods
**         (applicable only if these methods are enabled). The pointer
**         is set to address passed as the parameter - 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/
byte IEE1_EraseSector(IEE1_TAddress Addr)
{
  if(((dword)Addr < (dword)IEE1_AREA_START) || ((dword)Addr > (dword)IEE1_AREA_END)) { /* Is given address out of EEPROM area array ? */
    return ERR_RANGE;                  /* If yes then error */
  }
  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = Addr - 1U;              /* Store given address */
  /* FSTAT: ACCERR=1,FPVIOL=1 */
  FSTAT = 0x30U;                       /* Clear error flags */
  FCCOBIX = 0U;                        /* Clear index register */
  FCCOBHI = 0x12U;                     /* Erase D-Flash sector command */
  FCCOBLO = (byte)(((dword)Addr) >> 16); /* High address word */
  FCCOBIX++;                           /* Shift index register */
  FCCOB = (word)(((dword)Addr) & 0xFFFFFFFEUL); /* Low address word aligned to word*/
  FSTAT = 0x80U;                       /* Clear flag command complete */
  if (FSTAT_ACCERR) {                  /* Is access error or other error detected ? */
    return ERR_NOTAVAIL;               /* If yes then error */
  }
  if (IEE1_Wait) {                     /* Is the flag set ? */
    while (!FSTAT_CCIF) {}             /* If yes then wait for command completition */
    if (FSTAT_MGSTAT) {                /* Is an error detected ? */
      return ERR_NOTAVAIL;             /* If yes then error */
    }
  }
  return ERR_OK;                       /* OK */
}

/*lint -save  -e818 Disable MISRA rule (16.7) checking. */
/*
** ===================================================================
**     Method      :  IEE1_EraseEeprom (component IntEEPROM)
**
**     Description :
**         The method mass erases all EEPROM memory. The method also
**         sets address pointer for <SetActByte> and <GetActByte>
**         methods (applicable only if these methods are enabled). The
**         pointer is set to address passed as the parameter - 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Pass any valid EEPROM address. EEPROM
**                           module in some CPU families don't require
**                           address for mass erase, then the parameter
**                           is ignored.
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_NOTAVAIL - other device-specific error
** ===================================================================
*/
byte IEE1_EraseEeprom(IEE1_TAddress Addr)
{
  word i;
  IEE1_TAddress SectAddr;

  if(!FSTAT_CCIF) {                    /* Is reading from EEPROM possible? */
    return ERR_BUSY;                   /* If no then error */
  }
  EEPROMaddr = Addr - 1U;              /* Store given address */
  SectAddr = (IEE1_TAddress)0x0400UL;  /* D-Flash beginning */
  for(i = 0U;i < 0x0180U;i++) {
    /* FSTAT: ACCERR=1,FPVIOL=1 */
    FSTAT = 0x30U;                     /* Clear error flags */
    FCCOBIX = 0U;                      /* Clear index register */
    FCCOBHI = 0x12U;                   /* Erase D-Flash sector command */
    FCCOBLO = (byte)(((dword)SectAddr) >> 16); /* High address word */
    FCCOBIX++;                         /* Shift index register */
    FCCOB = (word)(((dword)SectAddr) & 0xFFFFFFFEUL); /* Low address word aligned to word*/
    FSTAT = 0x80U;                     /* Clear flag command complete */
    if (FSTAT_ACCERR) {                /* Is access error detected ? */
      return ERR_NOTAVAIL;             /* If yes then error */
    }
    if(i < 0x017FU) {                  /* If it is not the last sector */
      while (!FSTAT_CCIF) {}           /* then wait for command completition */
      if (FSTAT_MGSTAT) {              /* Is an error detected ? */
        return ERR_NOTAVAIL;           /* If yes then error */
      }
    }
    SectAddr = (IEE1_TAddress)((dword)SectAddr + 0x04U); /* Next sector */
  }
  if (IEE1_Wait) {                     /* Is the flag set ? */
    while (!FSTAT_CCIF) {}             /* If yes then wait for command completition */
    if (FSTAT_MGSTAT) {                /* Is an error detected ? */
      return ERR_NOTAVAIL;             /* If yes then error */
    }
  }
  return ERR_OK;                       /* OK */
}
/*lint -restore Enable MISRA rule (16.7) checking. */

/*
** ===================================================================
**     Method      :  IEE1_Init (component IntEEPROM)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void IEE1_Init(void)
{
  FCLKDIV = 0x07U;                     /* Set up Clock Divider Register */
  EEPROMaddr = (IEE1_TAddress)((dword)(IEE1_AREA_START) - 1U); /* Address of EEPROM which will be programmed/read */
  IEE1_Wait = TRUE;                    /* Wait in loop to command complete */
}

/*lint -restore Enable MISRA rule (11.3,11.4) checking. */

/* END IEE1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
