/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : IEE1.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : IntEEPROM
**     Version   : Component 02.200, Driver 01.25, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 29/07/2021, 17:49
**     Abstract  :
**         This device "IntEEPROM" implements internal EEPROM
**     Comment   :
**         The EEPROM array is organized as rows of word (2 bytes), the EEPROM block's
**         erase sector size is 2 rows (2 words). Therefore it is preferable
**         to use word aligned data for writting - methods SetWord and SetLong -
**         with word aligned address.
**         Driver expects that all security options of EEPROM are disabled.
**         If some security option is enabled methods performing write
**         operation (such as SetWord) can return error.
**     Settings  :
**         EEPROM size                 : 1536 byte
**         Initialization:
**              Wait in methods        : Enabled
**              EEPROM clock           : High: 1000 kHz
**
**     Contents  :
**         SetByte     - byte IEE1_SetByte(IEE1_TAddress Addr, byte Data);
**         GetByte     - byte IEE1_GetByte(IEE1_TAddress Addr, byte *Data);
**         SetWord     - byte IEE1_SetWord(IEE1_TAddress Addr, word Data);
**         GetWord     - byte IEE1_GetWord(IEE1_TAddress Addr, word *Data);
**         SetLong     - byte IEE1_SetLong(IEE1_TAddress Addr, dword Data);
**         GetLong     - byte IEE1_GetLong(IEE1_TAddress Addr, dword *Data);
**         SetActByte  - byte IEE1_SetActByte(byte Data);
**         GetActByte  - byte IEE1_GetActByte(byte *Data);
**         SetWait     - void IEE1_SetWait(bool Wait);
**         Busy        - bool IEE1_Busy(void);
**         EraseSector - byte IEE1_EraseSector(IEE1_TAddress Addr);
**         EraseEeprom - byte IEE1_EraseEeprom(IEE1_TAddress Addr);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __IEE1
#define __IEE1

/* MODULE IEE1. */

#include "Cpu.h"


#ifndef __BWUserType_IEE1_TAddress
#define __BWUserType_IEE1_TAddress
  /* User type for addressing of the EEPROM. Actual type depends on the CPU family. */
  typedef far word * far IEE1_TAddress; /* Type of address to the EEPROM */
#endif

#pragma CODE_SEG IEE1_CODE
#pragma DATA_SEG IEE1_DATA             /* Select data segment "IEE1_DATA" */


/* EEPROM area start address (in the format used by component methods). */
#define IEE1_AREA_START                 ((IEE1_TAddress)0x0400UL)
#define IEE1_AREA_START_INT             (0x0400UL)
/* EEPROM area last address (in the format used by component methods). */
#define IEE1_AREA_END                   ((IEE1_TAddress)0x09FFUL)
#define IEE1_AREA_END_INT               (0x09FFUL)
/* EEPROM area size (in bytes). */
#define IEE1_AREA_SIZE                  0x0600U
/* EEPROM area sector size: minimal erasable unit (in bytes). */
#define IEE1_AREA_SECTOR_SIZE           0x04U
/* TRUE if the component setting allows clear bits of already programmed flash memory location without destruction of the value in surrounding addresses by sector erase. */
#define IEE1_ALLOW_CLEAR                (TRUE)
/* Size of programming phrase, i.e. number of bytes that must be programmed at once */
#define IEE1_PROGRAMMING_PHRASE         (0x02U)

#define EEPROMStart IEE1_AREA_START    /* [DEPRECATED] Start address of used EEPROM array */
#define EEPROMEnd IEE1_AREA_END        /* [DEPRECATED] End address of used EEPROM array */

/* Flags parameter of OnError event can contain following error values (values may be OR-ed together) */
/* Double bit fault detect */
#define IEE1_DOUBLE_FAULT               (0x02U)
/* Single bit fault detect */
#define IEE1_SINGLE_FAULT               (0x01U)

/*EEPROM ADDRESSES*/
#define IEE1_AREA_START_11				 ((IEE1_TAddress)0x40BUL)

extern bool IEE1_Wait;                 /* Wait status of writting methods */

byte IEE1_SetByte(IEE1_TAddress Addr,byte Data);
/*
** ===================================================================
**     Method      :  IEE1_SetByte (component IntEEPROM)
**
**     Description :
**         This method writes a given byte to a specified address in
**         EEPROM. The method also sets address pointer for <SetActByte>
**         and <GetActByte> methods (applicable only if these methods
**         are enabled). The pointer is set to address passed as the
**         parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - parameter Addr is out of range
** ===================================================================
*/

byte IEE1_GetByte(IEE1_TAddress Addr,byte *Data);
/*
** ===================================================================
**     Method      :  IEE1_GetByte (component IntEEPROM)
**
**     Description :
**         This method reads a byte from a specified EEPROM address.
**         The method also sets address pointer for <SetActByte> and
**         <GetActByte> methods (applicable only if these methods are
**         enabled). The pointer is set to address passed as the
**         parameter.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - EEPROM Address
**       * Data            - A pointer to the returned 8-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - parameter Addr is out of range
** ===================================================================
*/

byte IEE1_SetWord(IEE1_TAddress Addr,word Data);
/*
** ===================================================================
**     Method      :  IEE1_SetWord (component IntEEPROM)
**
**     Description :
**         This method writes a given word (2 bytes) to the specified
**         address in EEPROM. The method also sets address pointer for
**         <SetActByte> and <GetActByte> methods (applicable only if
**         these methods are enabled). The pointer is set to address
**         passed as the parameter + 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/

byte IEE1_GetWord(IEE1_TAddress Addr,word *Data);
/*
** ===================================================================
**     Method      :  IEE1_GetWord (component IntEEPROM)
**
**     Description :
**         This method reads a word (2 bytes) from the specified EEPROM
**         address. The method also sets address pointer for
**         <SetActByte> and <GetActByte> methods (applicable only if
**         these methods are enabled). The pointer is set to address
**         passed as the parameter + 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**       * Data            - Pointer to returned 16-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/

byte IEE1_SetLong(IEE1_TAddress Addr,dword Data);
/*
** ===================================================================
**     Method      :  IEE1_SetLong (component IntEEPROM)
**
**     Description :
**         This method writes a given long word (4 bytes) to the
**         specified address in EEPROM. The method also sets address
**         pointer for <SetActByte> and <GetActByte> methods
**         (applicable only if these methods are enabled). The pointer
**         is set to address passed as the parameter + 3.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/

byte IEE1_GetLong(IEE1_TAddress Addr,dword *Data);
/*
** ===================================================================
**     Method      :  IEE1_GetLong (component IntEEPROM)
**
**     Description :
**         This method reads a long word (4 bytes) from the specified
**         EEPROM address. The method also sets address pointer for
**         <SetActByte> and <GetActByte> methods (applicable only if
**         these methods are enabled). The pointer is set to address
**         passed as the parameter + 3.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**       * Data            - A pointer to the returned 32-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/

byte IEE1_SetActByte(byte Data);
/*
** ===================================================================
**     Method      :  IEE1_SetActByte (component IntEEPROM)
**
**     Description :
**         This method writes given byte to the current address + 1
**         (The EEPROM address is pre-incremented) in EEPROM. The
**         address pointer is set by the methods using address as a
**         parameter, such as _/<GetByte>, <SetByte>/_,etc. - see help
**         of a specific method. Methods _/<GetPage>, <SetPage>/_ set
**         this pointer to the last address of the page.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Data            - Data to write
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_VALUE - verification of written data
**                           failed (read value does not match with
**                           written value) 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - current address pointer is
**                           out of range
** ===================================================================
*/

byte IEE1_GetActByte(byte *Data);
/*
** ===================================================================
**     Method      :  IEE1_GetActByte (component IntEEPROM)
**
**     Description :
**         This method reads the current byte +1 (address is
**         pre-incremented) from EEPROM.
**         The address pointer is set by the methods using address as a
**         parameter, such as _/<GetByte>, <SetByte>/_, etc. - see help
**         of a specific method._/<GetPage>, <SetPage>/_ set this
**         pointer to the last address of the page.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Data            - A pointer to the returned 8-bit data
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_BUSY - device is busy 
**                           - ERR_RANGE - current address pointer is
**                           out of range
** ===================================================================
*/

#define IEE1_SetWait(Wait) (IEE1_Wait = Wait)
/*
** ===================================================================
**     Method      :  IEE1_SetWait (component IntEEPROM)
**
**     Description :
**         This method changes the wait behavior of all writing methods.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Wait            - 
**                           <true> - methods wait till EEPROM write
**                           operation is finished, data is verified at
**                           the end of writing method
**                           <false> - methods do not wait for the end
**                           of EEPROM write operation, data is not
**                           verified at the end of writing method.
**     Returns     : Nothing
** ===================================================================
*/

#define IEE1_Busy() ((!FSTAT_CCIF) ? 1U:0U)
/*
** ===================================================================
**     Method      :  IEE1_Busy (component IntEEPROM)
**
**     Description :
**         Method returns the status of EEPROM device.
**     Parameters  : None
**     Returns     :
**         ---             -   - <true> if EEPROM is busy 
**                           - <false> if EEPROM is ready
** ===================================================================
*/

byte IEE1_EraseSector(IEE1_TAddress Addr);
/*
** ===================================================================
**     Method      :  IEE1_EraseSector (component IntEEPROM)
**
**     Description :
**         This method erases the smallest erasable area (sector) of
**         the EEPROM determined by given address. The method also sets
**         address pointer for <SetActByte> and <GetActByte> methods
**         (applicable only if these methods are enabled). The pointer
**         is set to address passed as the parameter - 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Address to EEPROM
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_NOTAVAIL - other device-specific
**                           error 
**                           - ERR_RANGE - selected address out of the
**                           selected address range
** ===================================================================
*/

byte IEE1_EraseEeprom(IEE1_TAddress Addr);
/*
** ===================================================================
**     Method      :  IEE1_EraseEeprom (component IntEEPROM)
**
**     Description :
**         The method mass erases all EEPROM memory. The method also
**         sets address pointer for <SetActByte> and <GetActByte>
**         methods (applicable only if these methods are enabled). The
**         pointer is set to address passed as the parameter - 1.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Addr            - Pass any valid EEPROM address. EEPROM
**                           module in some CPU families don't require
**                           address for mass erase, then the parameter
**                           is ignored.
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK 
**                           - ERR_SPEED - the component does not work
**                           in the active speed mode 
**                           - ERR_BUSY - device is busy 
**                           - ERR_NOTAVAIL - other device-specific error
** ===================================================================
*/

void IEE1_Init(void);
/*
** ===================================================================
**     Method      :  IEE1_Init (component IntEEPROM)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT

/* END IEE1. */

#endif /* ifndef __IEE1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
