/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PWM_Port_P.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_PWM
**     Version   : Component 01.165, Driver 01.14, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 28/07/2021, 12:05
**     Abstract  :
**          This file implements the PWM (from channel PWM0 to channel PWMx,
**          the actual count of PWM channels depends on the HCS12 derivative)
**          module initialization according to the Peripheral Initialization
**          settings, and defines interrupt service routines prototypes.
**          The Pulse Width Modulation (PWM) definition is based on the HC12
**          PWMdefinitions.Each of the six PWM channels has a programmable
**          period and duty cycle as well as a dedicated counter.A flexible
**          clock select scheme allows a total of four different clock sources
**          to be used with the counters. Each of the modulators can create
**          independent continuous waveforms with software-selectable duty
**          rates from 0% to 100%. The PWM outputs can be programmed as
**          left aligned outputs or center aligned outputs.
**     Settings  :
**          Component name                                 : PWM_Port_P
**          Device                                         : PWM
**          Settings                                       : 
**            Clock settings                               : 
**              Prescaler B select                         : 1
**              Clock B frequency                          : 500 kHz
**              Prescaler A select                         : 1
**              Clock A frequency                          : 500 kHz
**              Scale value of clock SB                    : 0
**              Clock SB frequency                         : 0.97 kHz
**              Scale value of clock SA                    : 0
**              Clock SA frequency                         : 0.97 kHz
**            Concatenate Channels 4 and 5                 : no
**            Concatenate Channels 2 and 3                 : no
**            Concatenate Channels 0 and 1                 : no
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**          Channels                                       : 2
**            Channel0                                     : 
**              Counter                                    : PWM0
**              PWM enabled                                : Enabled
**              Polarity                                   : Low to high
**              Clock Select                               : Clock A
**              Output Mode                                : Left Aligned
**              Channel Period                             : 0
**              Period time                                : -
**              Channel Duty                               : 0
**              Duty time                                  : -
**              Pin allocation                             : Enabled
**                Pin                                      : PP0_KWP0_ETRIG0_API_EXTCLK_PWM0
**                Pin signal                               : HBR_LSD_INA_PWM
**                Pull resistor                            : no initialization
**                Pin open drain                           : push-pull
**            Channel1                                     : 
**              Counter                                    : PWM1
**              PWM enabled                                : Enabled
**              Polarity                                   : Low to high
**              Clock Select                               : Clock A
**              Output Mode                                : Left Aligned
**              Channel Period                             : 0
**              Period time                                : -
**              Channel Duty                               : 0
**              Duty time                                  : -
**              Pin allocation                             : Enabled
**                Pin                                      : PP1_KWP1_ETRIG1_ECLKX2_PWM1
**                Pin signal                               : HBR_LSD_INB_PWM
**                Pull resistor                            : no initialization
**                Pin open drain                           : push-pull
**          Initialization                                 : 
**            Call Init method                             : yes
**     Contents  :
**         Init - void PWM_Port_P_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __PWM_Port_P
#define __PWM_Port_P

/* MODULE PWM_Port_P. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"




void PWM_Port_P_Init(void);
/*
** ===================================================================
**     Method      :  PWM_Port_P_Init (component Init_PWM)
**
**     Description :
**         This method initializes registers of the PWM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/


/* END PWM_Port_P. */

#endif /* ifndef __PWM_Port_P */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/

