/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SM1.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : SynchroMaster
**     Version   : Component 02.341, Driver 01.20, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 12/07/2022, 20:44
**     Abstract  :
**         This component "SynchroMaster" implements MASTER part of synchronous
**         serial master-slave communication.
**     Settings  :
**         Synchro type                : MASTER
**
**         Serial channel              : SPI0
**
**         Protocol
**             Init baud rate          : 0_320us
**             Clock edge              : rising
**             Width                   : 8 bits
**             Empty character         : 0
**             Empty char. on input    : RECEIVED
**
**         Registers
**             Input buffer            : SPI0DR    [$00DC]
**             Output buffer           : SPI0DR    [$00DC]
**             Control register        : SPI0CR1   [$00D8]
**             Mode register           : SPI0CR2   [$00D9]
**             Baud setting reg.       : SPI0BR    [$00DA]
**
**         Input interrupt
**             Vector name             : Vspi0
**             Priority                : 
**
**         Output interrupt
**             Vector name             : Vspi0
**             Priority                : 
**
**         Used pins                   :
**         ----------------------------------------------------------
**              Function    | On package |    Name
**         ----------------------------------------------------------
**               Input      |     27     |  PS4_PWM4_MISO0
**               Output     |     28     |  PS5_IOC4_MOSI0
**               Clock      |     29     |  PS6_IOC5_SCK0
**         ----------------------------------------------------------
**
**     Contents  :
**         Enable          - byte SM1_Enable(void);
**         Disable         - byte SM1_Disable(void);
**         RecvChar        - byte SM1_RecvChar(SM1_TComData *Chr);
**         SendChar        - byte SM1_SendChar(SM1_TComData Chr);
**         CharsInRxBuf    - byte SM1_CharsInRxBuf(word *Chr);
**         GetCharsInRxBuf - word SM1_GetCharsInRxBuf(void);
**         CharsInTxBuf    - byte SM1_CharsInTxBuf(word *Chr);
**         GetCharsInTxBuf - word SM1_GetCharsInTxBuf(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/


/* MODULE SM1. */

#include "SM1.h"
#include "CAN1.h"
#include "TIM1.h"
#include "GPIO_Port_S.h"
#include "ST25_IRQ.h"
#include "GPIO_Port_T.h"
#include "RTI1.h"
#include "IEE1.h"

#pragma DATA_SEG SM1_DATA              /* Select data segment "SM1_DATA" */
#pragma CODE_SEG SM1_CODE


#define OVERRUN_ERR      0x01U         /* Overrun error flag bit   */
#define CHAR_IN_RX       0x08U         /* Char is in RX buffer     */
#define FULL_TX          0x10U         /* Full transmit buffer     */
#define RUNINT_FROM_TX   0x20U         /* Interrupt is in progress */
#define FULL_RX          0x40U         /* Full receive buffer      */

static bool EnUser;                    /* Enable/Disable SPI */
static byte SerFlag;                   /* Flags for serial communication */
                                       /* Bits: 0 - OverRun error */
                                       /*       1 - Unused */
                                       /*       2 - Unused */
                                       /*       3 - Char in RX buffer */
                                       /*       4 - Full TX buffer */
                                       /*       5 - Running int from TX */
                                       /*       6 - Full RX buffer */
                                       /*       7 - Unused */
static SM1_TComData BufferRead;        /* Input char SPI commmunication */
static SM1_TComData BufferWrite;       /* Output char SPI commmunication */

/*
** ===================================================================
**     Method      :  SM1_Enable (component SynchroMaster)
**
**     Description :
**         Enable the component - it starts send and receive functions.
**         Events may be generated ("DisableEvent"/"EnableEvent"). This
**         method cannot be disabled if the Fault mode is enabled. It's
**         intended for re-enabling the module if fault occurred. For
**         more information please see the <"Fault mode" >property .
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SM1_Enable(void)
{
  if (!EnUser) {                       /* Is the device disabled by user? */
    EnUser = TRUE;                     /* If yes then set the flag "device enabled" */
    SPI0CR1_SPE = 1U;                  /* Enable device */
    SPI0CR1_SPIE = 1U;                 /* Enable interrupts */
    if (SerFlag & FULL_TX) {           /* Is any char in transmit buffer? */
      (void)SPI0SR;                    /* Read the status register */
      SPI0DRL = BufferWrite;           /* Store char to transmitter register */
    }
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SM1_Disable (component SynchroMaster)
**
**     Description :
**         Disable the component - it stops the send and receive
**         functions. No events will be generated. Note: When this
**         method is called while a transmission is in progress, the
**         data being transmitted/received may be lost.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SM1_Disable(void)
{
  if (EnUser) {                        /* Is the device enabled by user? */
    EnUser = FALSE;                    /* If yes then set the flag "device disabled" */
    SPI0CR1_SPE = 0U;                  /* Disable device */
    SPI0CR1_SPIE = 0U;                 /* Disable interrupts */
  }
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SM1_RecvChar (component SynchroMaster)
**
**     Description :
**         If any data is received, this method returns one character,
**         otherwise it returns an error code (it does not wait for
**         data). 
**         For information about SW overrun behavior please see
**         <General info page>.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the received character
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK - The valid data is received.
**                           ERR_SPEED - This device does not work in
**                           the active speed mode.
**                           ERR_RXEMPTY - No data in receiver.
**                           ERR_OVERRUN - Overrun error was detected
**                           from the last char or block received. In
**                           polling mode, this error code is returned
**                           only when the hardware supports detection
**                           of the overrun error. If interrupt service
**                           is enabled, and input buffer allocated by
**                           the component is full, the component
**                           behaviour depends on <Input buffer size>
**                           property : if property is 0, last received
**                           data-word is preserved (and previous is
**                           overwritten), if property is greater than 0,
**                           new received data-word are ignored.
**                           ERR_FAULT - Fault error was detected from
**                           the last char or block received. In the
**                           polling mode the ERR_FAULT is return until
**                           the user clear the fault flag bit, but in
**                           the interrupt mode ERR_FAULT is returned
**                           only once after the fault error occured.
**                           This error is supported only on the CPUs
**                           supports the faul mode function - where
**                           <Fault mode> property is available.
** ===================================================================
*/
byte SM1_RecvChar(SM1_TComData *Chr)
{
  byte FlagTmp;

  if ((SerFlag & CHAR_IN_RX) == 0U) {  /* Is any char in RX buffer? */
    return ERR_RXEMPTY;                /* If no then error */
  }
  EnterCritical();                     /* Enter the critical section */
  *Chr = BufferRead;                   /* Read the char */
  FlagTmp = SerFlag;                   /* Safe the flags */
  SerFlag &= (byte)(~(byte)(OVERRUN_ERR | CHAR_IN_RX | FULL_RX)); /* Clear flag "char in RX buffer" */
  ExitCritical();                      /* Exit the critical section */
  if ((FlagTmp & OVERRUN_ERR) != 0U) { /* Is the overrun occured? */
    return ERR_OVERRUN;                /* If yes then return error */
  } else {
    return ERR_OK;
  }
}

/*
** ===================================================================
**     Method      :  SM1_SendChar (component SynchroMaster)
**
**     Description :
**         Sends one character to the channel.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Chr             - Character to send
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_DISABLED - Device is disabled (only if
**                           output DMA is supported and enabled)
**                           ERR_TXFULL - Transmitter is full
** ===================================================================
*/
byte SM1_SendChar(SM1_TComData Chr)
{
  if (SerFlag & FULL_TX) {             /* Is any char in the TX buffer? */
    return ERR_TXFULL;                 /* If yes then error */
  }
  EnterCritical();                     /* Enter the critical section */
  BufferWrite = Chr;                   /* Store char to the temporary variable */
  if (EnUser) {                        /* Is the device enabled by user? */
    (void)SPI0SR;                      /* Read the status register */
    SPI0DRL = Chr;                     /* Store char to transmitter register */
  }
  SerFlag |= FULL_TX;                  /* Set the flag "full TX buffer" */
  ExitCritical();                      /* Exit the critical section */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SM1_CharsInRxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**         (deprecated method - Use the GetCharsInRxBuf method instead!)
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to number of characters in the
**                           input buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SM1_CharsInRxBuf(word *Chr)
{
  *Chr = (word)((SerFlag & CHAR_IN_RX)?(word)1U:(word)0U); /* Return number of chars in the receive buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SM1_GetCharsInRxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the input buffer.
**         Note: If the Interrupt service is disabled, and the Ignore
**         empty character is set to yes, and a character has been
**         received, then this method returns 1 although it was an
**         empty character.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the input buffer.
** ===================================================================
*/
word SM1_GetCharsInRxBuf(void)
{
  return (word)((SerFlag & CHAR_IN_RX)?(word)1U:(word)0U); /* Return number of chars in the receive buffer */
}
/*
** ===================================================================
**     Method      :  SM1_CharsInTxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer.
**         (deprecated method - Use the GetCharsInRxBuf method instead!)
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Chr             - A pointer to the number of characters in
**                           the output buffer
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte SM1_CharsInTxBuf(word *Chr)
{
  *Chr = ((SerFlag & FULL_TX) ? (word)1U : (word)0U); /* Return number of chars in the transmit buffer */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  SM1_GetCharsInTxBuf (component SynchroMaster)
**
**     Description :
**         Returns the number of characters in the output buffer.
**     Parameters  : None
**     Returns     :
**         ---             - Number of characters in the output buffer.
** ===================================================================
*/
word SM1_GetCharsInTxBuf(void)
{
  return ((SerFlag & FULL_TX) ? (word)1U : (word)0U); /* Return number of chars in the transmit buffer */
}
/*
** ===================================================================
**     Method      :  SM1_Interrupt (component SynchroMaster)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
#define ON_ERROR       0x01U
#define ON_FULL_RX     0x02U
#define ON_RX_CHAR     0x04U
#define ON_FREE_TX     0x08U
#define ON_TX_CHAR     0x10U
#define ON_RX_CHAR_EXT 0x20U
#pragma CODE_SEG __NEAR_SEG NON_BANKED
ISR(SM1_Interrupt)
{
  SM1_TComData Data = 0U;              /* Temporary variable for data */
  byte Status;                         /* Temporary variable for flags */

  Status = SPI0SR;                     /* Read the device error register */
  Data = SPI0DRL;                      /* Read data from receiver */
  if (SerFlag & CHAR_IN_RX) {          /* Is the overrun error flag set? */
    SerFlag |= OVERRUN_ERR;            /* If yes then set the OnError flag */
  }
  SerFlag |= CHAR_IN_RX;               /* Set flag "char in RX buffer" */
  BufferRead = Data;                   /* Read data from receiver */
  SerFlag &= (byte)(~(byte)FULL_TX);   /* Reset flag "full TX buffer" */
}

#pragma CODE_SEG SM1_CODE
/*
** ===================================================================
**     Method      :  SM1_Init (component SynchroMaster)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SM1_Init(void)
{
  /* SPI0CR1: SPIE=0,SPE=0,SPTIE=0,MSTR=0,CPOL=0,CPHA=1,SSOE=0,LSBFE=0 */
  SPI0CR1 = 0x04U;                     /* Reset the device register */
  (void)SPI0SR;                        /* Read the status register */
  (void)SPI0DRL;                       /* Read the device register */
  /* SPI0BR: ??=0,SPPR2=0,SPPR1=0,SPPR0=0,??=0,SPR2=0,SPR1=1,SPR0=0 */
  SPI0BR = 0x02U;                      /* Set the baud rate register */
  /* SPI0CR2: ??=0,XFRW=0,??=0,MODFEN=0,BIDIROE=0,??=0,SPISWAI=0,SPC0=0 */
  SPI0CR2 = 0x00U;                     /* Set control register 2 */
  /* SPI0CR1: SPIE=1,SPE=1,SPTIE=0,MSTR=1,CPOL=0,CPHA=1,SSOE=0,LSBFE=1 */
  SPI0CR1 = 0xD5U;                     /* Set control register 1 */
  SerFlag = 0U;                        /* Reset all flags */
  EnUser = TRUE;                       /* Enable device */
}


/* END SM1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
