/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SPI_SS.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.16, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 13/07/2022, 08:22
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       10            |  PP1_KWP1_ETRIG1_ECLKX2_PWM1
**             ----------------------------------------------------
**
**         Port name                   : P
**
**         Bit number (in port)        : 1
**         Bit mask of the port        : $0002
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : off
**
**         Port data register          : PTP       [$0258]
**         Port control register       : DDRP      [$025A]
**
**         Optimization for            : speed
**     Contents  :
**         GetVal - bool SPI_SS_GetVal(void);
**         PutVal - void SPI_SS_PutVal(bool Val);
**         ClrVal - void SPI_SS_ClrVal(void);
**         SetVal - void SPI_SS_SetVal(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef SPI_SS_H_
#define SPI_SS_H_

/* MODULE SPI_SS. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG SPI_SS_CODE
/*
** ===================================================================
**     Method      :  SPI_SS_GetVal (component BitIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pin and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Output direction only.
**     Parameters  : None
**     Returns     :
**         ---             - Input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)

** ===================================================================
*/
#define SPI_SS_GetVal() ( \
    (bool)((getReg8(PTP) & 0x02U))     /* Return port data */ \
  )

/*
** ===================================================================
**     Method      :  SPI_SS_PutVal (component BitIO)
**
**     Description :
**         This method writes the new output value.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Val             - Output value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
**     Returns     : Nothing
** ===================================================================
*/
void SPI_SS_PutVal(bool Val);

/*
** ===================================================================
**     Method      :  SPI_SS_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define SPI_SS_ClrVal() ( \
    (void)clrReg8Bits(PTP, 0x02U)      /* PTP1=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  SPI_SS_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define SPI_SS_SetVal() ( \
    (void)setReg8Bits(PTP, 0x02U)      /* PTP1=0x01U */ \
  )

#pragma CODE_SEG DEFAULT

/* END SPI_SS. */
#endif /* #ifndef __SPI_SS_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
