/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : ST25_IRQ.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : ExtInt
**     Version   : Component 02.094, Driver 01.21, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 13/07/2022, 08:22
**     Abstract  :
**         This component "ExtInt" implements an external 
**         interrupt, its control methods and interrupt/event 
**         handling procedure.
**         The component uses one pin which generates interrupt on 
**         selected edge.
**     Settings  :
**         Interrupt name              : Vportad
**         User handling procedure     : ST25_IRQ_Interrupt
**
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       23            |  PAD6_KWAD6_AN6_ACMPP
**             ----------------------------------------------------
**
**         Port name                   : ADL
**
**         Bit number (in port)        : 6
**         Bit mask of the port        : $0040
**
**         Signal edge/level           : rising
**         Pull option                 : off
**         Initial state               : Enabled
**
**         Edge register               : PPS01AD   [$027A]
**         Enable register             : PIE01AD   [$027C]
**         Request register            : PIF01AD   [$027E]
**
**         Port data register          : PT1AD     [$0271]
**         Port control register       : DDR1AD    [$0275]
**     Contents  :
**         Enable  - void ST25_IRQ_Enable(void);
**         Disable - void ST25_IRQ_Disable(void);
**         GetVal  - bool ST25_IRQ_GetVal(void);
**         SetEdge - byte ST25_IRQ_SetEdge(byte edge);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __ST25_IRQ_H
#define __ST25_IRQ_H

/* MODULE ST25_IRQ. */

/*Including shared modules, which are used in the whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Events.h"
#include "Cpu.h"

#pragma CODE_SEG ST25_IRQ_CODE


void ST25_IRQ_Enable(void);
/*
** ===================================================================
**     Method      :  ST25_IRQ_Enable (component ExtInt)
**
**     Description :
**         Enable the component - the external events are accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define ST25_IRQ_Disable() (PIE01AD_PIE1AD6 = 0U) /* Disable interrupt "Vportad" */
/*
** ===================================================================
**     Method      :  ST25_IRQ_Disable (component ExtInt)
**
**     Description :
**         Disable the component - the external events are not accepted.
**         This method is available only if HW module allows
**         enable/disable of the interrupt.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#pragma CODE_SEG __NEAR_SEG NON_BANKED
__interrupt void ST25_IRQ_Interrupt(void);
#pragma CODE_SEG ST25_IRQ_CODE
/*
** ===================================================================
**     Method      :  ST25_IRQ_Interrupt (component ExtInt)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes the components event(s).
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#define ST25_IRQ_GetVal() (PT1AD & 0x40U)
/*
** ===================================================================
**     Method      :  ST25_IRQ_GetVal (component ExtInt)
**
**     Description :
**         Returns the actual value of the input pin of the component.
**     Parameters  : None
**     Returns     :
**         ---             - Returned input value. Possible values:
**                           FALSE - logical "0" (Low level)
**                           TRUE - logical "1" (High level)
** ===================================================================
*/

byte ST25_IRQ_SetEdge(byte edge);
/*
** ===================================================================
**     Method      :  ST25_IRQ_SetEdge (component ExtInt)
**
**     Description :
**         Sets the edge type for this component that generates the
**         interrupt.
**     Parameters  :
**         NAME            - DESCRIPTION
**         edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
** ===================================================================
*/



#pragma CODE_SEG DEFAULT

/* END ST25_IRQ. */

#endif /* __ST25_IRQ_H*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
