/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TIM1.c
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_TIM
**     Version   : Component 01.244, Driver 01.12, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 28/07/2021, 12:05
**     Abstract  :
**          This file implements the TIM (TIM_Counter) 
**          module initialization according to the Peripheral Initialization 
**          Component settings, and defines interrupt service routines prototypes.
**          The basic timer consists of a 16-bit, software-programmable counter 
**          driven by a seven-stage programmable prescaler.
**          This timer can be used for many purposes, including input waveform
**          measurements while simultaneously generating an output waveform. 
**          Pulse widths can vary from microseconds to many seconds.
**     Settings  :
**          Component name                                 : TIM1
**          Device                                         : TIM
**          Settings                                       : 
**            Clock settings                               : 
**              Precision Timer                            : Disabled
**              Prescaler                                  : Bus Clock / 1
**              Frequency                                  : 500 kHz
**              Clock                                      : Timer prescaler
**            Fast Flag Clear                              : no
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**            Channels                                     : 0
**          Interrupts                                     : 
**            Timer overflow                               : 
**              Timer overflow                             : Disabled
**              Interrupt                                  : Vtimovf
**              Priority                                   : 1
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Timer                                        : Disabled
**     Contents  :
**         Init - void TIM1_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE TIM1. */

#include "TIM1.h"

/*
** ===================================================================
**     Method      :  TIM1_Init (component Init_TIM)
**
**     Description :
**         This method initializes registers of the TIM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void TIM1_Init(void)
{
  /* TSCR1: TEN=0 */
  clrReg8Bits(TSCR1, 0x80U);            
  /* TIE: ??=0,??=0,C5I=0,C4I=0,C3I=0,C2I=0,C1I=0,C0I=0 */
  setReg8(TIE, 0x00U);                  
  /* TIOS: ??=0,??=0,IOS5=0,IOS4=0,IOS3=0,IOS2=0,IOS1=0,IOS0=0 */
  setReg8(TIOS, 0x00U);                 
  /* OCPD: ??=0,??=0,OCPD5=0,OCPD4=0,OCPD3=0,OCPD2=0,OCPD1=0,OCPD0=0 */
  setReg8(OCPD, 0x00U);                 
  /* TTOV: ??=0,??=0,TOV5=0,TOV4=0,TOV3=0,TOV2=0,TOV1=0,TOV0=0 */
  setReg8(TTOV, 0x00U);                 
  /* TCTL1: ??=0,??=0,??=0,??=0,OM5=0,OL5=0,OM4=0,OL4=0 */
  setReg8(TCTL1, 0x00U);                
  /* TCTL2: OM3=0,OL3=0,OM2=0,OL2=0,OM1=0,OL1=0,OM0=0,OL0=0 */
  setReg8(TCTL2, 0x00U);                
  /* TCTL3: ??=0,??=0,??=0,??=0,EDG5B=0,EDG5A=0,EDG4B=0,EDG4A=0 */
  setReg8(TCTL3, 0x00U);                
  /* TCTL4: EDG3B=0,EDG3A=0,EDG2B=0,EDG2A=0,EDG1B=0,EDG1A=0,EDG0B=0,EDG0A=0 */
  setReg8(TCTL4, 0x00U);                
  /* TFLG1: ??=0,??=0,C5F=1,C4F=1,C3F=1,C2F=1,C1F=1,C0F=1 */
  setReg8(TFLG1, 0x3FU);                
  /* TFLG2: TOF=1,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg8(TFLG2, 0x80U);                
  /* TIE: ??=0,??=0,C5I=0,C4I=0,C3I=0,C2I=0,C1I=0,C0I=0 */
  setReg8(TIE, 0x00U);                  
  /* TSCR2: TOI=0,??=0,??=0,??=0,??=0,PR2=0,PR1=0,PR0=0 */
  setReg8(TSCR2, 0x00U);                
  /* PTPSR: PTPS7=0,PTPS6=0,PTPS5=0,PTPS4=0,PTPS3=0,PTPS2=0,PTPS1=0,PTPS0=0 */
  setReg8(PTPSR, 0x00U);                
  /* TSCR1: TEN=0,TSWAI=0,TSFRZ=0,TFFCA=0,PRNT=0,??=0,??=0,??=0 */
  setReg8(TSCR1, 0x00U);                
}

/* END TIM1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
