/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : TIM1.h
**     Project   : Generic_Latch_Bootloader
**     Processor : MC9S12G48VLC
**     Component : Init_TIM
**     Version   : Component 01.244, Driver 01.12, CPU db: 3.00.020
**     Compiler  : CodeWarrior HC12 C Compiler
**     Date/Time : 28/07/2021, 12:05
**     Abstract  :
**          This file implements the TIM (TIM_Counter) 
**          module initialization according to the Peripheral Initialization 
**          Component settings, and defines interrupt service routines prototypes.
**          The basic timer consists of a 16-bit, software-programmable counter 
**          driven by a seven-stage programmable prescaler.
**          This timer can be used for many purposes, including input waveform
**          measurements while simultaneously generating an output waveform. 
**          Pulse widths can vary from microseconds to many seconds.
**     Settings  :
**          Component name                                 : TIM1
**          Device                                         : TIM
**          Settings                                       : 
**            Clock settings                               : 
**              Precision Timer                            : Disabled
**              Prescaler                                  : Bus Clock / 1
**              Frequency                                  : 500 kHz
**              Clock                                      : Timer prescaler
**            Fast Flag Clear                              : no
**            Stop in wait mode                            : no
**            Stop in freeze mode                          : no
**            Channels                                     : 0
**          Interrupts                                     : 
**            Timer overflow                               : 
**              Timer overflow                             : Disabled
**              Interrupt                                  : Vtimovf
**              Priority                                   : 1
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : yes
**            Timer                                        : Disabled
**     Contents  :
**         Init - void TIM1_Init(void);
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __TIM1
#define __TIM1

/* MODULE TIM1. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited components */

#include "Cpu.h"


void TIM1_Init(void);
/*
** ===================================================================
**     Method      :  TIM1_Init (component Init_TIM)
**
**     Description :
**         This method initializes registers of the TIM module
**         according to this Peripheral Initialization settings. Call
**         this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END TIM1. */
#endif /* ifndef __TIM1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.05 [04.46]
**     for the Freescale HCS12 series of microcontrollers.
**
** ###################################################################
*/
